insert into pedido (id_produto, nome, preco) values (1, 'Mouthwatering Teriyaki Tofu Bowl', 34.99);
insert into pedido (id_produto, nome, preco) values (2, 'Deluxe Seafood Platter', 3.29);
insert into pedido (id_produto, nome, preco) values (3, 'Deluxe Seafood Platter', 34.99);
insert into pedido (id_produto, nome, preco) values (4, 'Crispy Parmesan Chicken', 7.49);
insert into pedido (id_produto, nome, preco) values (5, 'Spicy Jalapeno Burger', 3.29);
insert into pedido (id_produto, nome, preco) values (6, 'Hearty Beef Stew', 1.89);
insert into pedido (id_produto, nome, preco) values (7, 'Sweet Honey BBQ Wings', 39.99);
insert into pedido (id_produto, nome, preco) values (8, 'Wholesome Quinoa Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (9, 'Cheesy Bacon Macaroni', 129.99);
insert into pedido (id_produto, nome, preco) values (10, 'Sizzling BBQ Ribs', 79.99);
insert into pedido (id_produto, nome, preco) values (11, 'Zesty Lemon Salmon', 18.99);
insert into pedido (id_produto, nome, preco) values (12, 'Zesty Lemon Salmon', 2.49);
insert into pedido (id_produto, nome, preco) values (13, 'Gourmet Truffle Fries', 2.79);
insert into pedido (id_produto, nome, preco) values (14, 'Succulent Pulled Pork Sandwich', 49.99);
insert into pedido (id_produto, nome, preco) values (15, 'Flavorful Veggie Stir-Fry', 3.29);
insert into pedido (id_produto, nome, preco) values (16, 'Wholesome Quinoa Salad', 4.99);
insert into pedido (id_produto, nome, preco) values (17, 'Succulent Pulled Pork Sandwich', 39.99);
insert into pedido (id_produto, nome, preco) values (18, 'Wholesome Quinoa Salad', 1.29);
insert into pedido (id_produto, nome, preco) values (19, 'Succulent Pulled Pork Sandwich', 199.99);
insert into pedido (id_produto, nome, preco) values (20, 'Cheesy Bacon Macaroni', 7.99);
insert into pedido (id_produto, nome, preco) values (21, 'Gourmet Truffle Fries', 3.29);
insert into pedido (id_produto, nome, preco) values (22, 'Succulent Pulled Pork Sandwich', 2.79);
insert into pedido (id_produto, nome, preco) values (23, 'Crispy Parmesan Chicken', 58.99);
insert into pedido (id_produto, nome, preco) values (24, 'Spicy Jalapeno Burger', 19.99);
insert into pedido (id_produto, nome, preco) values (25, 'Refreshing Watermelon Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (26, 'Spicy Jalapeno Burger', 69.99);
insert into pedido (id_produto, nome, preco) values (27, 'Savory Garlic Shrimp Pasta', 2.99);
insert into pedido (id_produto, nome, preco) values (28, 'Decadent Chocolate Lava Cake', 2.99);
insert into pedido (id_produto, nome, preco) values (29, 'Zesty Lemon Salmon', 4.99);
insert into pedido (id_produto, nome, preco) values (30, 'Zesty Lemon Salmon', 4.29);
insert into pedido (id_produto, nome, preco) values (31, 'Decadent Chocolate Lava Cake', 15.99);
insert into pedido (id_produto, nome, preco) values (32, 'Creamy Mushroom Risotto', 7.49);
insert into pedido (id_produto, nome, preco) values (33, 'Decadent Chocolate Lava Cake', 1.99);
insert into pedido (id_produto, nome, preco) values (34, 'Mouthwatering Teriyaki Tofu Bowl', 2.29);
insert into pedido (id_produto, nome, preco) values (35, 'Gourmet Truffle Fries', 29.99);
insert into pedido (id_produto, nome, preco) values (36, 'Flavorful Veggie Stir-Fry', 29.99);
insert into pedido (id_produto, nome, preco) values (37, 'Flavorful Veggie Stir-Fry', 3.29);
insert into pedido (id_produto, nome, preco) values (38, 'Decadent Chocolate Lava Cake', 22.99);
insert into pedido (id_produto, nome, preco) values (39, 'Refreshing Watermelon Salad', 4.99);
insert into pedido (id_produto, nome, preco) values (40, 'Sizzling BBQ Ribs', 4.99);
insert into pedido (id_produto, nome, preco) values (41, 'Gourmet Truffle Fries', 49.99);
insert into pedido (id_produto, nome, preco) values (42, 'Homestyle Apple Pie', 39.99);
insert into pedido (id_produto, nome, preco) values (43, 'Mouthwatering Teriyaki Tofu Bowl', 2.39);
insert into pedido (id_produto, nome, preco) values (44, 'Mouthwatering Teriyaki Tofu Bowl', 1.79);
insert into pedido (id_produto, nome, preco) values (45, 'Cheesy Bacon Macaroni', 12.99);
insert into pedido (id_produto, nome, preco) values (46, 'Sizzling BBQ Ribs', 3.79);
insert into pedido (id_produto, nome, preco) values (47, 'Crispy Parmesan Chicken', 2.99);
insert into pedido (id_produto, nome, preco) values (48, 'Hearty Beef Stew', 14.99);
insert into pedido (id_produto, nome, preco) values (49, 'Refreshing Watermelon Salad', 39.99);
insert into pedido (id_produto, nome, preco) values (50, 'Zesty Lemon Salmon', 5.29);
insert into pedido (id_produto, nome, preco) values (51, 'Cheesy Bacon Macaroni', 0.75);
insert into pedido (id_produto, nome, preco) values (52, 'Spicy Jalapeno Burger', 5.99);
insert into pedido (id_produto, nome, preco) values (53, 'Succulent Pulled Pork Sandwich', 24.99);
insert into pedido (id_produto, nome, preco) values (54, 'Wholesome Quinoa Salad', 5.29);
insert into pedido (id_produto, nome, preco) values (55, 'Cheesy Bacon Macaroni', 3.29);
insert into pedido (id_produto, nome, preco) values (56, 'Sizzling BBQ Ribs', 34.99);
insert into pedido (id_produto, nome, preco) values (57, 'Deluxe Seafood Platter', 34.99);
insert into pedido (id_produto, nome, preco) values (58, 'Cheesy Bacon Macaroni', 79.99);
insert into pedido (id_produto, nome, preco) values (59, 'Wholesome Quinoa Salad', 39.99);
insert into pedido (id_produto, nome, preco) values (60, 'Sweet Honey BBQ Wings', 39.99);
insert into pedido (id_produto, nome, preco) values (61, 'Refreshing Watermelon Salad', 4.49);
insert into pedido (id_produto, nome, preco) values (62, 'Sweet Honey BBQ Wings', 34.99);
insert into pedido (id_produto, nome, preco) values (63, 'Spicy Jalapeno Burger', 2.89);
insert into pedido (id_produto, nome, preco) values (64, 'Hearty Beef Stew', 1.29);
insert into pedido (id_produto, nome, preco) values (65, 'Exotic Mango Tango Smoothie', 1.79);
insert into pedido (id_produto, nome, preco) values (66, 'Tangy Orange Glazed Duck', 24.99);
insert into pedido (id_produto, nome, preco) values (67, 'Crispy Parmesan Chicken', 99.99);
insert into pedido (id_produto, nome, preco) values (68, 'Flavorful Veggie Stir-Fry', 14.99);
insert into pedido (id_produto, nome, preco) values (69, 'Savory Garlic Shrimp Pasta', 2.49);
insert into pedido (id_produto, nome, preco) values (70, 'Tangy Orange Glazed Duck', 14.99);
insert into pedido (id_produto, nome, preco) values (71, 'Hearty Beef Stew', 3.79);
insert into pedido (id_produto, nome, preco) values (72, 'Homestyle Apple Pie', 3.99);
insert into pedido (id_produto, nome, preco) values (73, 'Hearty Beef Stew', 1.29);
insert into pedido (id_produto, nome, preco) values (74, 'Deluxe Seafood Platter', 2.99);
insert into pedido (id_produto, nome, preco) values (75, 'Savory Garlic Shrimp Pasta', 34.99);
insert into pedido (id_produto, nome, preco) values (76, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (77, 'Hearty Beef Stew', 14.99);
insert into pedido (id_produto, nome, preco) values (78, 'Spicy Jalapeno Burger', 12.99);
insert into pedido (id_produto, nome, preco) values (79, 'Wholesome Quinoa Salad', 2.89);
insert into pedido (id_produto, nome, preco) values (80, 'Flavorful Veggie Stir-Fry', 69.99);
insert into pedido (id_produto, nome, preco) values (81, 'Tangy Orange Glazed Duck', 39.99);
insert into pedido (id_produto, nome, preco) values (82, 'Zesty Lemon Salmon', 5.49);
insert into pedido (id_produto, nome, preco) values (83, 'Refreshing Watermelon Salad', 1.29);
insert into pedido (id_produto, nome, preco) values (84, 'Mouthwatering Teriyaki Tofu Bowl', 9.99);
insert into pedido (id_produto, nome, preco) values (85, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (86, 'Sweet Honey BBQ Wings', 89.99);
insert into pedido (id_produto, nome, preco) values (87, 'Flavorful Veggie Stir-Fry', 2.99);
insert into pedido (id_produto, nome, preco) values (88, 'Hearty Beef Stew', 4.99);
insert into pedido (id_produto, nome, preco) values (89, 'Flavorful Veggie Stir-Fry', 3.29);
insert into pedido (id_produto, nome, preco) values (90, 'Spicy Jalapeno Burger', 359.99);
insert into pedido (id_produto, nome, preco) values (91, 'Refreshing Watermelon Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (92, 'Succulent Pulled Pork Sandwich', 22.99);
insert into pedido (id_produto, nome, preco) values (93, 'Homestyle Apple Pie', 29.99);
insert into pedido (id_produto, nome, preco) values (94, 'Cheesy Bacon Macaroni', 2.99);
insert into pedido (id_produto, nome, preco) values (95, 'Crispy Parmesan Chicken', 5.99);
insert into pedido (id_produto, nome, preco) values (96, 'Homestyle Apple Pie', 22);
insert into pedido (id_produto, nome, preco) values (97, 'Homestyle Apple Pie', 99.99);
insert into pedido (id_produto, nome, preco) values (98, 'Wholesome Quinoa Salad', 22.99);
insert into pedido (id_produto, nome, preco) values (99, 'Exotic Mango Tango Smoothie', 12.99);
insert into pedido (id_produto, nome, preco) values (100, 'Hearty Beef Stew', 69.99);
insert into pedido (id_produto, nome, preco) values (101, 'Spicy Jalapeno Burger', 15.99);
insert into pedido (id_produto, nome, preco) values (102, 'Mouthwatering Teriyaki Tofu Bowl', 18.99);
insert into pedido (id_produto, nome, preco) values (103, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (104, 'Sweet Honey BBQ Wings', 12.99);
insert into pedido (id_produto, nome, preco) values (105, 'Mouthwatering Teriyaki Tofu Bowl', 1.89);
insert into pedido (id_produto, nome, preco) values (106, 'Mouthwatering Teriyaki Tofu Bowl', 4.49);
insert into pedido (id_produto, nome, preco) values (107, 'Spicy Jalapeno Burger', 99.99);
insert into pedido (id_produto, nome, preco) values (108, 'Flavorful Veggie Stir-Fry', 14.99);
insert into pedido (id_produto, nome, preco) values (109, 'Hearty Beef Stew', 19.99);
insert into pedido (id_produto, nome, preco) values (110, 'Zesty Lemon Salmon', 1.29);
insert into pedido (id_produto, nome, preco) values (111, 'Sweet Honey BBQ Wings', 29.99);
insert into pedido (id_produto, nome, preco) values (112, 'Zesty Lemon Salmon', 69.99);
insert into pedido (id_produto, nome, preco) values (113, 'Decadent Chocolate Lava Cake', 1.29);
insert into pedido (id_produto, nome, preco) values (114, 'Mouthwatering Teriyaki Tofu Bowl', 4.49);
insert into pedido (id_produto, nome, preco) values (115, 'Spicy Jalapeno Burger', 2.99);
insert into pedido (id_produto, nome, preco) values (116, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (117, 'Savory Garlic Shrimp Pasta', 59.99);
insert into pedido (id_produto, nome, preco) values (118, 'Spicy Jalapeno Burger', 49.99);
insert into pedido (id_produto, nome, preco) values (119, 'Sweet Honey BBQ Wings', 4.99);
insert into pedido (id_produto, nome, preco) values (120, 'Deluxe Seafood Platter', 199.99);
insert into pedido (id_produto, nome, preco) values (121, 'Spicy Jalapeno Burger', 199.99);
insert into pedido (id_produto, nome, preco) values (122, 'Crispy Parmesan Chicken', 12.99);
insert into pedido (id_produto, nome, preco) values (123, 'Savory Garlic Shrimp Pasta', 19.99);
insert into pedido (id_produto, nome, preco) values (124, 'Savory Garlic Shrimp Pasta', 1.99);
insert into pedido (id_produto, nome, preco) values (125, 'Refreshing Watermelon Salad', 1.99);
insert into pedido (id_produto, nome, preco) values (126, 'Exotic Mango Tango Smoothie', 39.99);
insert into pedido (id_produto, nome, preco) values (127, 'Savory Garlic Shrimp Pasta', 79.99);
insert into pedido (id_produto, nome, preco) values (128, 'Savory Garlic Shrimp Pasta', 2.29);
insert into pedido (id_produto, nome, preco) values (129, 'Creamy Mushroom Risotto', 22.99);
insert into pedido (id_produto, nome, preco) values (130, 'Savory Garlic Shrimp Pasta', 1.99);
insert into pedido (id_produto, nome, preco) values (131, 'Refreshing Watermelon Salad', 5.29);
insert into pedido (id_produto, nome, preco) values (132, 'Refreshing Watermelon Salad', 5.99);
insert into pedido (id_produto, nome, preco) values (133, 'Flavorful Veggie Stir-Fry', 4.49);
insert into pedido (id_produto, nome, preco) values (134, 'Sizzling BBQ Ribs', 39.99);
insert into pedido (id_produto, nome, preco) values (135, 'Crispy Parmesan Chicken', 1.29);
insert into pedido (id_produto, nome, preco) values (136, 'Deluxe Seafood Platter', 4.99);
insert into pedido (id_produto, nome, preco) values (137, 'Decadent Chocolate Lava Cake', 99.99);
insert into pedido (id_produto, nome, preco) values (138, 'Sweet Honey BBQ Wings', 14.99);
insert into pedido (id_produto, nome, preco) values (139, 'Gourmet Truffle Fries', 3.29);
insert into pedido (id_produto, nome, preco) values (140, 'Refreshing Watermelon Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (141, 'Exotic Mango Tango Smoothie', 24.99);
insert into pedido (id_produto, nome, preco) values (142, 'Exotic Mango Tango Smoothie', 1.49);
insert into pedido (id_produto, nome, preco) values (143, 'Decadent Chocolate Lava Cake', 59.99);
insert into pedido (id_produto, nome, preco) values (144, 'Crispy Parmesan Chicken', 4.19);
insert into pedido (id_produto, nome, preco) values (145, 'Crispy Parmesan Chicken', 1.89);
insert into pedido (id_produto, nome, preco) values (146, 'Spicy Jalapeno Burger', 24.99);
insert into pedido (id_produto, nome, preco) values (147, 'Spicy Jalapeno Burger', 39.99);
insert into pedido (id_produto, nome, preco) values (148, 'Gourmet Truffle Fries', 3.19);
insert into pedido (id_produto, nome, preco) values (149, 'Wholesome Quinoa Salad', 2.49);
insert into pedido (id_produto, nome, preco) values (150, 'Cheesy Bacon Macaroni', 24.99);
insert into pedido (id_produto, nome, preco) values (151, 'Decadent Chocolate Lava Cake', 1.79);
insert into pedido (id_produto, nome, preco) values (152, 'Cheesy Bacon Macaroni', 24.99);
insert into pedido (id_produto, nome, preco) values (153, 'Gourmet Truffle Fries', 24.99);
insert into pedido (id_produto, nome, preco) values (154, 'Deluxe Seafood Platter', 5.99);
insert into pedido (id_produto, nome, preco) values (155, 'Zesty Lemon Salmon', 9.99);
insert into pedido (id_produto, nome, preco) values (156, 'Hearty Beef Stew', 79.99);
insert into pedido (id_produto, nome, preco) values (157, 'Sizzling BBQ Ribs', 89.99);
insert into pedido (id_produto, nome, preco) values (158, 'Hearty Beef Stew', 49.99);
insert into pedido (id_produto, nome, preco) values (159, 'Exotic Mango Tango Smoothie', 2.99);
insert into pedido (id_produto, nome, preco) values (160, 'Creamy Mushroom Risotto', 19.99);
insert into pedido (id_produto, nome, preco) values (161, 'Refreshing Watermelon Salad', 59.99);
insert into pedido (id_produto, nome, preco) values (162, 'Zesty Lemon Salmon', 2.49);
insert into pedido (id_produto, nome, preco) values (163, 'Creamy Mushroom Risotto', 5.49);
insert into pedido (id_produto, nome, preco) values (164, 'Tangy Orange Glazed Duck', 99.99);
insert into pedido (id_produto, nome, preco) values (165, 'Hearty Beef Stew', 4.29);
insert into pedido (id_produto, nome, preco) values (166, 'Gourmet Truffle Fries', 8.99);
insert into pedido (id_produto, nome, preco) values (167, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (168, 'Mouthwatering Teriyaki Tofu Bowl', 64.99);
insert into pedido (id_produto, nome, preco) values (169, 'Sizzling BBQ Ribs', 4.99);
insert into pedido (id_produto, nome, preco) values (170, 'Creamy Mushroom Risotto', 29.99);
insert into pedido (id_produto, nome, preco) values (171, 'Wholesome Quinoa Salad', 79.99);
insert into pedido (id_produto, nome, preco) values (172, 'Refreshing Watermelon Salad', 39.99);
insert into pedido (id_produto, nome, preco) values (173, 'Tangy Orange Glazed Duck', 64.99);
insert into pedido (id_produto, nome, preco) values (174, 'Tangy Orange Glazed Duck', 34.99);
insert into pedido (id_produto, nome, preco) values (175, 'Wholesome Quinoa Salad', 79.99);
insert into pedido (id_produto, nome, preco) values (176, 'Refreshing Watermelon Salad', 89.99);
insert into pedido (id_produto, nome, preco) values (177, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (178, 'Mouthwatering Teriyaki Tofu Bowl', 59.99);
insert into pedido (id_produto, nome, preco) values (179, 'Tangy Orange Glazed Duck', 3.99);
insert into pedido (id_produto, nome, preco) values (180, 'Refreshing Watermelon Salad', 34.99);
insert into pedido (id_produto, nome, preco) values (181, 'Zesty Lemon Salmon', 9.99);
insert into pedido (id_produto, nome, preco) values (182, 'Exotic Mango Tango Smoothie', 89.99);
insert into pedido (id_produto, nome, preco) values (183, 'Spicy Jalapeno Burger', 3.99);
insert into pedido (id_produto, nome, preco) values (184, 'Spicy Jalapeno Burger', 2.49);
insert into pedido (id_produto, nome, preco) values (185, 'Decadent Chocolate Lava Cake', 1.99);
insert into pedido (id_produto, nome, preco) values (186, 'Flavorful Veggie Stir-Fry', 24.99);
insert into pedido (id_produto, nome, preco) values (187, 'Creamy Mushroom Risotto', 29.99);
insert into pedido (id_produto, nome, preco) values (188, 'Succulent Pulled Pork Sandwich', 39.99);
insert into pedido (id_produto, nome, preco) values (189, 'Sweet Honey BBQ Wings', 59.99);
insert into pedido (id_produto, nome, preco) values (190, 'Sweet Honey BBQ Wings', 3.29);
insert into pedido (id_produto, nome, preco) values (191, 'Exotic Mango Tango Smoothie', 2.49);
insert into pedido (id_produto, nome, preco) values (192, 'Sizzling BBQ Ribs', 34.99);
insert into pedido (id_produto, nome, preco) values (193, 'Cheesy Bacon Macaroni', 34.99);
insert into pedido (id_produto, nome, preco) values (194, 'Succulent Pulled Pork Sandwich', 12.99);
insert into pedido (id_produto, nome, preco) values (195, 'Flavorful Veggie Stir-Fry', 24.99);
insert into pedido (id_produto, nome, preco) values (196, 'Spicy Jalapeno Burger', 3.29);
insert into pedido (id_produto, nome, preco) values (197, 'Cheesy Bacon Macaroni', 99.99);
insert into pedido (id_produto, nome, preco) values (198, 'Decadent Chocolate Lava Cake', 29.99);
insert into pedido (id_produto, nome, preco) values (199, 'Hearty Beef Stew', 3.79);
insert into pedido (id_produto, nome, preco) values (200, 'Creamy Mushroom Risotto', 39.99);
insert into pedido (id_produto, nome, preco) values (201, 'Flavorful Veggie Stir-Fry', 34.99);
insert into pedido (id_produto, nome, preco) values (202, 'Refreshing Watermelon Salad', 4.19);
insert into pedido (id_produto, nome, preco) values (203, 'Cheesy Bacon Macaroni', 5.49);
insert into pedido (id_produto, nome, preco) values (204, 'Exotic Mango Tango Smoothie', 8.99);
insert into pedido (id_produto, nome, preco) values (205, 'Gourmet Truffle Fries', 19.99);
insert into pedido (id_produto, nome, preco) values (206, 'Mouthwatering Teriyaki Tofu Bowl', 1.89);
insert into pedido (id_produto, nome, preco) values (207, 'Refreshing Watermelon Salad', 15.99);
insert into pedido (id_produto, nome, preco) values (208, 'Spicy Jalapeno Burger', 69.99);
insert into pedido (id_produto, nome, preco) values (209, 'Cheesy Bacon Macaroni', 5.99);
insert into pedido (id_produto, nome, preco) values (210, 'Tangy Orange Glazed Duck', 49.99);
insert into pedido (id_produto, nome, preco) values (211, 'Zesty Lemon Salmon', 3.49);
insert into pedido (id_produto, nome, preco) values (212, 'Exotic Mango Tango Smoothie', 5.29);
insert into pedido (id_produto, nome, preco) values (213, 'Decadent Chocolate Lava Cake', 79.99);
insert into pedido (id_produto, nome, preco) values (214, 'Creamy Mushroom Risotto', 15.99);
insert into pedido (id_produto, nome, preco) values (215, 'Wholesome Quinoa Salad', 19.99);
insert into pedido (id_produto, nome, preco) values (216, 'Flavorful Veggie Stir-Fry', 2.99);
insert into pedido (id_produto, nome, preco) values (217, 'Hearty Beef Stew', 54.99);
insert into pedido (id_produto, nome, preco) values (218, 'Creamy Mushroom Risotto', 2.99);
insert into pedido (id_produto, nome, preco) values (219, 'Zesty Lemon Salmon', 2.69);
insert into pedido (id_produto, nome, preco) values (220, 'Flavorful Veggie Stir-Fry', 1.49);
insert into pedido (id_produto, nome, preco) values (221, 'Spicy Jalapeno Burger', 3.29);
insert into pedido (id_produto, nome, preco) values (222, 'Sizzling BBQ Ribs', 4.99);
insert into pedido (id_produto, nome, preco) values (223, 'Sweet Honey BBQ Wings', 1.5);
insert into pedido (id_produto, nome, preco) values (224, 'Decadent Chocolate Lava Cake', 4.49);
insert into pedido (id_produto, nome, preco) values (225, 'Homestyle Apple Pie', 18.99);
insert into pedido (id_produto, nome, preco) values (226, 'Zesty Lemon Salmon', 24.99);
insert into pedido (id_produto, nome, preco) values (227, 'Homestyle Apple Pie', 5.99);
insert into pedido (id_produto, nome, preco) values (228, 'Succulent Pulled Pork Sandwich', 25.99);
insert into pedido (id_produto, nome, preco) values (229, 'Sizzling BBQ Ribs', 49.99);
insert into pedido (id_produto, nome, preco) values (230, 'Hearty Beef Stew', 5.49);
insert into pedido (id_produto, nome, preco) values (231, 'Tangy Orange Glazed Duck', 4.99);
insert into pedido (id_produto, nome, preco) values (232, 'Mouthwatering Teriyaki Tofu Bowl', 34.99);
insert into pedido (id_produto, nome, preco) values (233, 'Deluxe Seafood Platter', 3.29);
insert into pedido (id_produto, nome, preco) values (234, 'Hearty Beef Stew', 299.99);
insert into pedido (id_produto, nome, preco) values (235, 'Creamy Mushroom Risotto', 44.99);
insert into pedido (id_produto, nome, preco) values (236, 'Zesty Lemon Salmon', 29.99);
insert into pedido (id_produto, nome, preco) values (237, 'Mouthwatering Teriyaki Tofu Bowl', 24.99);
insert into pedido (id_produto, nome, preco) values (238, 'Sweet Honey BBQ Wings', 39.99);
insert into pedido (id_produto, nome, preco) values (239, 'Gourmet Truffle Fries', 139.99);
insert into pedido (id_produto, nome, preco) values (240, 'Crispy Parmesan Chicken', 2.99);
insert into pedido (id_produto, nome, preco) values (241, 'Succulent Pulled Pork Sandwich', 19.99);
insert into pedido (id_produto, nome, preco) values (242, 'Savory Garlic Shrimp Pasta', 129.99);
insert into pedido (id_produto, nome, preco) values (243, 'Tangy Orange Glazed Duck', 4.49);
insert into pedido (id_produto, nome, preco) values (244, 'Creamy Mushroom Risotto', 24.99);
insert into pedido (id_produto, nome, preco) values (245, 'Gourmet Truffle Fries', 3.49);
insert into pedido (id_produto, nome, preco) values (246, 'Decadent Chocolate Lava Cake', 7.49);
insert into pedido (id_produto, nome, preco) values (247, 'Creamy Mushroom Risotto', 24.99);
insert into pedido (id_produto, nome, preco) values (248, 'Flavorful Veggie Stir-Fry', 19.99);
insert into pedido (id_produto, nome, preco) values (249, 'Spicy Jalapeno Burger', 34.99);
insert into pedido (id_produto, nome, preco) values (250, 'Homestyle Apple Pie', 8.49);
insert into pedido (id_produto, nome, preco) values (251, 'Gourmet Truffle Fries', 3.49);
insert into pedido (id_produto, nome, preco) values (252, 'Gourmet Truffle Fries', 2.29);
insert into pedido (id_produto, nome, preco) values (253, 'Crispy Parmesan Chicken', 4.99);
insert into pedido (id_produto, nome, preco) values (254, 'Crispy Parmesan Chicken', 29.99);
insert into pedido (id_produto, nome, preco) values (255, 'Savory Garlic Shrimp Pasta', 4.99);
insert into pedido (id_produto, nome, preco) values (256, 'Deluxe Seafood Platter', 5.99);
insert into pedido (id_produto, nome, preco) values (257, 'Cheesy Bacon Macaroni', 29.99);
insert into pedido (id_produto, nome, preco) values (258, 'Sizzling BBQ Ribs', 2.49);
insert into pedido (id_produto, nome, preco) values (259, 'Refreshing Watermelon Salad', 5.49);
insert into pedido (id_produto, nome, preco) values (260, 'Crispy Parmesan Chicken', 129.99);
insert into pedido (id_produto, nome, preco) values (261, 'Cheesy Bacon Macaroni', 3.99);
insert into pedido (id_produto, nome, preco) values (262, 'Creamy Mushroom Risotto', 3.79);
insert into pedido (id_produto, nome, preco) values (263, 'Sweet Honey BBQ Wings', 7.99);
insert into pedido (id_produto, nome, preco) values (264, 'Succulent Pulled Pork Sandwich', 25.99);
insert into pedido (id_produto, nome, preco) values (265, 'Decadent Chocolate Lava Cake', 5.99);
insert into pedido (id_produto, nome, preco) values (266, 'Succulent Pulled Pork Sandwich', 19.99);
insert into pedido (id_produto, nome, preco) values (267, 'Creamy Mushroom Risotto', 5.59);
insert into pedido (id_produto, nome, preco) values (268, 'Tangy Orange Glazed Duck', 29.99);
insert into pedido (id_produto, nome, preco) values (269, 'Sizzling BBQ Ribs', 3.69);
insert into pedido (id_produto, nome, preco) values (270, 'Cheesy Bacon Macaroni', 4.99);
insert into pedido (id_produto, nome, preco) values (271, 'Succulent Pulled Pork Sandwich', 29.99);
insert into pedido (id_produto, nome, preco) values (272, 'Flavorful Veggie Stir-Fry', 49.99);
insert into pedido (id_produto, nome, preco) values (273, 'Sweet Honey BBQ Wings', 199.99);
insert into pedido (id_produto, nome, preco) values (274, 'Cheesy Bacon Macaroni', 109.99);
insert into pedido (id_produto, nome, preco) values (275, 'Homestyle Apple Pie', 8.99);
insert into pedido (id_produto, nome, preco) values (276, 'Cheesy Bacon Macaroni', 3.99);
insert into pedido (id_produto, nome, preco) values (277, 'Decadent Chocolate Lava Cake', 25.99);
insert into pedido (id_produto, nome, preco) values (278, 'Cheesy Bacon Macaroni', 39.99);
insert into pedido (id_produto, nome, preco) values (279, 'Deluxe Seafood Platter', 5.99);
insert into pedido (id_produto, nome, preco) values (280, 'Homestyle Apple Pie', 99.99);
insert into pedido (id_produto, nome, preco) values (281, 'Hearty Beef Stew', 4.99);
insert into pedido (id_produto, nome, preco) values (282, 'Exotic Mango Tango Smoothie', 2.99);
insert into pedido (id_produto, nome, preco) values (283, 'Deluxe Seafood Platter', 1.79);
insert into pedido (id_produto, nome, preco) values (284, 'Homestyle Apple Pie', 24.99);
insert into pedido (id_produto, nome, preco) values (285, 'Succulent Pulled Pork Sandwich', 14.99);
insert into pedido (id_produto, nome, preco) values (286, 'Hearty Beef Stew', 3.99);
insert into pedido (id_produto, nome, preco) values (287, 'Cheesy Bacon Macaroni', 2.49);
insert into pedido (id_produto, nome, preco) values (288, 'Deluxe Seafood Platter', 29.99);
insert into pedido (id_produto, nome, preco) values (289, 'Creamy Mushroom Risotto', 3.29);
insert into pedido (id_produto, nome, preco) values (290, 'Cheesy Bacon Macaroni', 39.99);
insert into pedido (id_produto, nome, preco) values (291, 'Flavorful Veggie Stir-Fry', 2.99);
insert into pedido (id_produto, nome, preco) values (292, 'Sweet Honey BBQ Wings', 54.99);
insert into pedido (id_produto, nome, preco) values (293, 'Sizzling BBQ Ribs', 7.99);
insert into pedido (id_produto, nome, preco) values (294, 'Wholesome Quinoa Salad', 49.99);
insert into pedido (id_produto, nome, preco) values (295, 'Exotic Mango Tango Smoothie', 3.69);
insert into pedido (id_produto, nome, preco) values (296, 'Flavorful Veggie Stir-Fry', 29.99);
insert into pedido (id_produto, nome, preco) values (297, 'Spicy Jalapeno Burger', 3.89);
insert into pedido (id_produto, nome, preco) values (298, 'Exotic Mango Tango Smoothie', 2.99);
insert into pedido (id_produto, nome, preco) values (299, 'Flavorful Veggie Stir-Fry', 4.99);
insert into pedido (id_produto, nome, preco) values (300, 'Savory Garlic Shrimp Pasta', 3.29);
insert into pedido (id_produto, nome, preco) values (301, 'Zesty Lemon Salmon', 45);
insert into pedido (id_produto, nome, preco) values (302, 'Crispy Parmesan Chicken', 39.99);
insert into pedido (id_produto, nome, preco) values (303, 'Hearty Beef Stew', 19.99);
insert into pedido (id_produto, nome, preco) values (304, 'Tangy Orange Glazed Duck', 3.99);
insert into pedido (id_produto, nome, preco) values (305, 'Creamy Mushroom Risotto', 2.79);
insert into pedido (id_produto, nome, preco) values (306, 'Decadent Chocolate Lava Cake', 3.49);
insert into pedido (id_produto, nome, preco) values (307, 'Spicy Jalapeno Burger', 4.99);
insert into pedido (id_produto, nome, preco) values (308, 'Sweet Honey BBQ Wings', 14.99);
insert into pedido (id_produto, nome, preco) values (309, 'Sweet Honey BBQ Wings', 89.99);
insert into pedido (id_produto, nome, preco) values (310, 'Gourmet Truffle Fries', 5.99);
insert into pedido (id_produto, nome, preco) values (311, 'Hearty Beef Stew', 19.99);
insert into pedido (id_produto, nome, preco) values (312, 'Deluxe Seafood Platter', 24.99);
insert into pedido (id_produto, nome, preco) values (313, 'Gourmet Truffle Fries', 34.99);
insert into pedido (id_produto, nome, preco) values (314, 'Sweet Honey BBQ Wings', 25.99);
insert into pedido (id_produto, nome, preco) values (315, 'Succulent Pulled Pork Sandwich', 19.99);
insert into pedido (id_produto, nome, preco) values (316, 'Gourmet Truffle Fries', 59.99);
insert into pedido (id_produto, nome, preco) values (317, 'Mouthwatering Teriyaki Tofu Bowl', 2.49);
insert into pedido (id_produto, nome, preco) values (318, 'Spicy Jalapeno Burger', 59.99);
insert into pedido (id_produto, nome, preco) values (319, 'Wholesome Quinoa Salad', 3.99);
insert into pedido (id_produto, nome, preco) values (320, 'Mouthwatering Teriyaki Tofu Bowl', 39.99);
insert into pedido (id_produto, nome, preco) values (321, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (322, 'Savory Garlic Shrimp Pasta', 2.99);
insert into pedido (id_produto, nome, preco) values (323, 'Exotic Mango Tango Smoothie', 39.99);
insert into pedido (id_produto, nome, preco) values (324, 'Cheesy Bacon Macaroni', 14.99);
insert into pedido (id_produto, nome, preco) values (325, 'Homestyle Apple Pie', 3.99);
insert into pedido (id_produto, nome, preco) values (326, 'Exotic Mango Tango Smoothie', 29.99);
insert into pedido (id_produto, nome, preco) values (327, 'Cheesy Bacon Macaroni', 6.99);
insert into pedido (id_produto, nome, preco) values (328, 'Zesty Lemon Salmon', 3.49);
insert into pedido (id_produto, nome, preco) values (329, 'Hearty Beef Stew', 29.99);
insert into pedido (id_produto, nome, preco) values (330, 'Hearty Beef Stew', 24.99);
insert into pedido (id_produto, nome, preco) values (331, 'Succulent Pulled Pork Sandwich', 4.99);
insert into pedido (id_produto, nome, preco) values (332, 'Crispy Parmesan Chicken', 89.99);
insert into pedido (id_produto, nome, preco) values (333, 'Homestyle Apple Pie', 2.99);
insert into pedido (id_produto, nome, preco) values (334, 'Creamy Mushroom Risotto', 39.99);
insert into pedido (id_produto, nome, preco) values (335, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (336, 'Crispy Parmesan Chicken', 24.99);
insert into pedido (id_produto, nome, preco) values (337, 'Zesty Lemon Salmon', 39.99);
insert into pedido (id_produto, nome, preco) values (338, 'Flavorful Veggie Stir-Fry', 24.99);
insert into pedido (id_produto, nome, preco) values (339, 'Spicy Jalapeno Burger', 1.49);
insert into pedido (id_produto, nome, preco) values (340, 'Flavorful Veggie Stir-Fry', 22.99);
insert into pedido (id_produto, nome, preco) values (341, 'Zesty Lemon Salmon', 29.99);
insert into pedido (id_produto, nome, preco) values (342, 'Creamy Mushroom Risotto', 49.99);
insert into pedido (id_produto, nome, preco) values (343, 'Succulent Pulled Pork Sandwich', 54.99);
insert into pedido (id_produto, nome, preco) values (344, 'Succulent Pulled Pork Sandwich', 3.99);
insert into pedido (id_produto, nome, preco) values (345, 'Succulent Pulled Pork Sandwich', 39.99);
insert into pedido (id_produto, nome, preco) values (346, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (347, 'Hearty Beef Stew', 89.99);
insert into pedido (id_produto, nome, preco) values (348, 'Exotic Mango Tango Smoothie', 3.99);
insert into pedido (id_produto, nome, preco) values (349, 'Crispy Parmesan Chicken', 5.99);
insert into pedido (id_produto, nome, preco) values (350, 'Hearty Beef Stew', 24.99);
insert into pedido (id_produto, nome, preco) values (351, 'Tangy Orange Glazed Duck', 4.49);
insert into pedido (id_produto, nome, preco) values (352, 'Mouthwatering Teriyaki Tofu Bowl', 34.99);
insert into pedido (id_produto, nome, preco) values (353, 'Spicy Jalapeno Burger', 44.99);
insert into pedido (id_produto, nome, preco) values (354, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (355, 'Zesty Lemon Salmon', 2.49);
insert into pedido (id_produto, nome, preco) values (356, 'Decadent Chocolate Lava Cake', 6.49);
insert into pedido (id_produto, nome, preco) values (357, 'Refreshing Watermelon Salad', 4.49);
insert into pedido (id_produto, nome, preco) values (358, 'Hearty Beef Stew', 2.49);
insert into pedido (id_produto, nome, preco) values (359, 'Mouthwatering Teriyaki Tofu Bowl', 12.99);
insert into pedido (id_produto, nome, preco) values (360, 'Hearty Beef Stew', 39.99);
insert into pedido (id_produto, nome, preco) values (361, 'Sweet Honey BBQ Wings', 14.99);
insert into pedido (id_produto, nome, preco) values (362, 'Sweet Honey BBQ Wings', 19.99);
insert into pedido (id_produto, nome, preco) values (363, 'Cheesy Bacon Macaroni', 89.99);
insert into pedido (id_produto, nome, preco) values (364, 'Refreshing Watermelon Salad', 10.99);
insert into pedido (id_produto, nome, preco) values (365, 'Spicy Jalapeno Burger', 6.99);
insert into pedido (id_produto, nome, preco) values (366, 'Homestyle Apple Pie', 3.49);
insert into pedido (id_produto, nome, preco) values (367, 'Refreshing Watermelon Salad', 3.99);
insert into pedido (id_produto, nome, preco) values (368, 'Creamy Mushroom Risotto', 2.49);
insert into pedido (id_produto, nome, preco) values (369, 'Homestyle Apple Pie', 14.99);
insert into pedido (id_produto, nome, preco) values (370, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (371, 'Refreshing Watermelon Salad', 1.99);
insert into pedido (id_produto, nome, preco) values (372, 'Gourmet Truffle Fries', 49.99);
insert into pedido (id_produto, nome, preco) values (373, 'Succulent Pulled Pork Sandwich', 79.99);
insert into pedido (id_produto, nome, preco) values (374, 'Cheesy Bacon Macaroni', 2.49);
insert into pedido (id_produto, nome, preco) values (375, 'Zesty Lemon Salmon', 3.99);
insert into pedido (id_produto, nome, preco) values (376, 'Savory Garlic Shrimp Pasta', 39.99);
insert into pedido (id_produto, nome, preco) values (377, 'Flavorful Veggie Stir-Fry', 5.99);
insert into pedido (id_produto, nome, preco) values (378, 'Cheesy Bacon Macaroni', 54.99);
insert into pedido (id_produto, nome, preco) values (379, 'Sizzling BBQ Ribs', 5.49);
insert into pedido (id_produto, nome, preco) values (380, 'Savory Garlic Shrimp Pasta', 9.99);
insert into pedido (id_produto, nome, preco) values (381, 'Tangy Orange Glazed Duck', 3.49);
insert into pedido (id_produto, nome, preco) values (382, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (383, 'Flavorful Veggie Stir-Fry', 3.99);
insert into pedido (id_produto, nome, preco) values (384, 'Savory Garlic Shrimp Pasta', 3.29);
insert into pedido (id_produto, nome, preco) values (385, 'Gourmet Truffle Fries', 34.99);
insert into pedido (id_produto, nome, preco) values (386, 'Spicy Jalapeno Burger', 3.99);
insert into pedido (id_produto, nome, preco) values (387, 'Zesty Lemon Salmon', 3.99);
insert into pedido (id_produto, nome, preco) values (388, 'Wholesome Quinoa Salad', 4.29);
insert into pedido (id_produto, nome, preco) values (389, 'Deluxe Seafood Platter', 3.79);
insert into pedido (id_produto, nome, preco) values (390, 'Tangy Orange Glazed Duck', 7.99);
insert into pedido (id_produto, nome, preco) values (391, 'Savory Garlic Shrimp Pasta', 24.99);
insert into pedido (id_produto, nome, preco) values (392, 'Decadent Chocolate Lava Cake', 7.99);
insert into pedido (id_produto, nome, preco) values (393, 'Homestyle Apple Pie', 39.99);
insert into pedido (id_produto, nome, preco) values (394, 'Hearty Beef Stew', 3.99);
insert into pedido (id_produto, nome, preco) values (395, 'Spicy Jalapeno Burger', 99.99);
insert into pedido (id_produto, nome, preco) values (396, 'Sweet Honey BBQ Wings', 2.99);
insert into pedido (id_produto, nome, preco) values (397, 'Sweet Honey BBQ Wings', 19.99);
insert into pedido (id_produto, nome, preco) values (398, 'Deluxe Seafood Platter', 9.99);
insert into pedido (id_produto, nome, preco) values (399, 'Savory Garlic Shrimp Pasta', 19.99);
insert into pedido (id_produto, nome, preco) values (400, 'Cheesy Bacon Macaroni', 4.79);
insert into pedido (id_produto, nome, preco) values (401, 'Mouthwatering Teriyaki Tofu Bowl', 5.99);
insert into pedido (id_produto, nome, preco) values (402, 'Exotic Mango Tango Smoothie', 9.99);
insert into pedido (id_produto, nome, preco) values (403, 'Succulent Pulled Pork Sandwich', 29.99);
insert into pedido (id_produto, nome, preco) values (404, 'Deluxe Seafood Platter', 4.29);
insert into pedido (id_produto, nome, preco) values (405, 'Wholesome Quinoa Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (406, 'Refreshing Watermelon Salad', 3.29);
insert into pedido (id_produto, nome, preco) values (407, 'Succulent Pulled Pork Sandwich', 24.99);
insert into pedido (id_produto, nome, preco) values (408, 'Homestyle Apple Pie', 39.99);
insert into pedido (id_produto, nome, preco) values (409, 'Wholesome Quinoa Salad', 2.79);
insert into pedido (id_produto, nome, preco) values (410, 'Exotic Mango Tango Smoothie', 15.99);
insert into pedido (id_produto, nome, preco) values (411, 'Wholesome Quinoa Salad', 19.99);
insert into pedido (id_produto, nome, preco) values (412, 'Zesty Lemon Salmon', 4.79);
insert into pedido (id_produto, nome, preco) values (413, 'Creamy Mushroom Risotto', 5.99);
insert into pedido (id_produto, nome, preco) values (414, 'Sweet Honey BBQ Wings', 10.99);
insert into pedido (id_produto, nome, preco) values (415, 'Exotic Mango Tango Smoothie', 25.99);
insert into pedido (id_produto, nome, preco) values (416, 'Refreshing Watermelon Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (417, 'Sizzling BBQ Ribs', 18.99);
insert into pedido (id_produto, nome, preco) values (418, 'Refreshing Watermelon Salad', 39.99);
insert into pedido (id_produto, nome, preco) values (419, 'Crispy Parmesan Chicken', 24.99);
insert into pedido (id_produto, nome, preco) values (420, 'Mouthwatering Teriyaki Tofu Bowl', 1.39);
insert into pedido (id_produto, nome, preco) values (421, 'Spicy Jalapeno Burger', 3.99);
insert into pedido (id_produto, nome, preco) values (422, 'Hearty Beef Stew', 19.99);
insert into pedido (id_produto, nome, preco) values (423, 'Tangy Orange Glazed Duck', 5.49);
insert into pedido (id_produto, nome, preco) values (424, 'Sizzling BBQ Ribs', 59.99);
insert into pedido (id_produto, nome, preco) values (425, 'Sizzling BBQ Ribs', 79.99);
insert into pedido (id_produto, nome, preco) values (426, 'Savory Garlic Shrimp Pasta', 9.99);
insert into pedido (id_produto, nome, preco) values (427, 'Gourmet Truffle Fries', 4.49);
insert into pedido (id_produto, nome, preco) values (428, 'Homestyle Apple Pie', 6.99);
insert into pedido (id_produto, nome, preco) values (429, 'Sizzling BBQ Ribs', 5.49);
insert into pedido (id_produto, nome, preco) values (430, 'Deluxe Seafood Platter', 3.29);
insert into pedido (id_produto, nome, preco) values (431, 'Crispy Parmesan Chicken', 109.99);
insert into pedido (id_produto, nome, preco) values (432, 'Gourmet Truffle Fries', 9.99);
insert into pedido (id_produto, nome, preco) values (433, 'Sizzling BBQ Ribs', 19.99);
insert into pedido (id_produto, nome, preco) values (434, 'Tangy Orange Glazed Duck', 22.99);
insert into pedido (id_produto, nome, preco) values (435, 'Decadent Chocolate Lava Cake', 1.79);
insert into pedido (id_produto, nome, preco) values (436, 'Sweet Honey BBQ Wings', 24.99);
insert into pedido (id_produto, nome, preco) values (437, 'Sizzling BBQ Ribs', 59.99);
insert into pedido (id_produto, nome, preco) values (438, 'Wholesome Quinoa Salad', 1.79);
insert into pedido (id_produto, nome, preco) values (439, 'Sizzling BBQ Ribs', 3.29);
insert into pedido (id_produto, nome, preco) values (440, 'Spicy Jalapeno Burger', 3.99);
insert into pedido (id_produto, nome, preco) values (441, 'Tangy Orange Glazed Duck', 39.99);
insert into pedido (id_produto, nome, preco) values (442, 'Cheesy Bacon Macaroni', 29.99);
insert into pedido (id_produto, nome, preco) values (443, 'Succulent Pulled Pork Sandwich', 12.99);
insert into pedido (id_produto, nome, preco) values (444, 'Deluxe Seafood Platter', 16.99);
insert into pedido (id_produto, nome, preco) values (445, 'Crispy Parmesan Chicken', 3.99);
insert into pedido (id_produto, nome, preco) values (446, 'Flavorful Veggie Stir-Fry', 19.99);
insert into pedido (id_produto, nome, preco) values (447, 'Wholesome Quinoa Salad', 79.99);
insert into pedido (id_produto, nome, preco) values (448, 'Zesty Lemon Salmon', 12.99);
insert into pedido (id_produto, nome, preco) values (449, 'Exotic Mango Tango Smoothie', 19.99);
insert into pedido (id_produto, nome, preco) values (450, 'Tangy Orange Glazed Duck', 15.99);
insert into pedido (id_produto, nome, preco) values (451, 'Crispy Parmesan Chicken', 39.99);
insert into pedido (id_produto, nome, preco) values (452, 'Decadent Chocolate Lava Cake', 39.99);
insert into pedido (id_produto, nome, preco) values (453, 'Crispy Parmesan Chicken', 34.99);
insert into pedido (id_produto, nome, preco) values (454, 'Wholesome Quinoa Salad', 4.49);
insert into pedido (id_produto, nome, preco) values (455, 'Zesty Lemon Salmon', 2.89);
insert into pedido (id_produto, nome, preco) values (456, 'Succulent Pulled Pork Sandwich', 4.49);
insert into pedido (id_produto, nome, preco) values (457, 'Gourmet Truffle Fries', 19.99);
insert into pedido (id_produto, nome, preco) values (458, 'Hearty Beef Stew', 4.99);
insert into pedido (id_produto, nome, preco) values (459, 'Wholesome Quinoa Salad', 29.99);
insert into pedido (id_produto, nome, preco) values (460, 'Wholesome Quinoa Salad', 2.49);
insert into pedido (id_produto, nome, preco) values (461, 'Crispy Parmesan Chicken', 10.99);
insert into pedido (id_produto, nome, preco) values (462, 'Hearty Beef Stew', 4.99);
insert into pedido (id_produto, nome, preco) values (463, 'Savory Garlic Shrimp Pasta', 12.99);
insert into pedido (id_produto, nome, preco) values (464, 'Mouthwatering Teriyaki Tofu Bowl', 3.29);
insert into pedido (id_produto, nome, preco) values (465, 'Crispy Parmesan Chicken', 2.99);
insert into pedido (id_produto, nome, preco) values (466, 'Refreshing Watermelon Salad', 3.99);
insert into pedido (id_produto, nome, preco) values (467, 'Sweet Honey BBQ Wings', 24.99);
insert into pedido (id_produto, nome, preco) values (468, 'Decadent Chocolate Lava Cake', 5.99);
insert into pedido (id_produto, nome, preco) values (469, 'Creamy Mushroom Risotto', 3.29);
insert into pedido (id_produto, nome, preco) values (470, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (471, 'Mouthwatering Teriyaki Tofu Bowl', 49.99);
insert into pedido (id_produto, nome, preco) values (472, 'Exotic Mango Tango Smoothie', 22.99);
insert into pedido (id_produto, nome, preco) values (473, 'Exotic Mango Tango Smoothie', 5.49);
insert into pedido (id_produto, nome, preco) values (474, 'Refreshing Watermelon Salad', 4.79);
insert into pedido (id_produto, nome, preco) values (475, 'Refreshing Watermelon Salad', 59.99);
insert into pedido (id_produto, nome, preco) values (476, 'Succulent Pulled Pork Sandwich', 2.99);
insert into pedido (id_produto, nome, preco) values (477, 'Zesty Lemon Salmon', 3.99);
insert into pedido (id_produto, nome, preco) values (478, 'Exotic Mango Tango Smoothie', 3.49);
insert into pedido (id_produto, nome, preco) values (479, 'Wholesome Quinoa Salad', 3.29);
insert into pedido (id_produto, nome, preco) values (480, 'Flavorful Veggie Stir-Fry', 19.99);
insert into pedido (id_produto, nome, preco) values (481, 'Spicy Jalapeno Burger', 6.49);
insert into pedido (id_produto, nome, preco) values (482, 'Succulent Pulled Pork Sandwich', 4.99);
insert into pedido (id_produto, nome, preco) values (483, 'Zesty Lemon Salmon', 39.99);
insert into pedido (id_produto, nome, preco) values (484, 'Crispy Parmesan Chicken', 8.99);
insert into pedido (id_produto, nome, preco) values (485, 'Creamy Mushroom Risotto', 3.49);
insert into pedido (id_produto, nome, preco) values (486, 'Creamy Mushroom Risotto', 129.99);
insert into pedido (id_produto, nome, preco) values (487, 'Refreshing Watermelon Salad', 7.49);
insert into pedido (id_produto, nome, preco) values (488, 'Creamy Mushroom Risotto', 39.99);
insert into pedido (id_produto, nome, preco) values (489, 'Decadent Chocolate Lava Cake', 89.99);
insert into pedido (id_produto, nome, preco) values (490, 'Mouthwatering Teriyaki Tofu Bowl', 2.59);
insert into pedido (id_produto, nome, preco) values (491, 'Wholesome Quinoa Salad', 34.99);
insert into pedido (id_produto, nome, preco) values (492, 'Mouthwatering Teriyaki Tofu Bowl', 6.89);
insert into pedido (id_produto, nome, preco) values (493, 'Zesty Lemon Salmon', 29.99);
insert into pedido (id_produto, nome, preco) values (494, 'Tangy Orange Glazed Duck', 2.49);
insert into pedido (id_produto, nome, preco) values (495, 'Sweet Honey BBQ Wings', 2.99);
insert into pedido (id_produto, nome, preco) values (496, 'Savory Garlic Shrimp Pasta', 5.99);
insert into pedido (id_produto, nome, preco) values (497, 'Cheesy Bacon Macaroni', 3.29);
insert into pedido (id_produto, nome, preco) values (498, 'Flavorful Veggie Stir-Fry', 3.49);
insert into pedido (id_produto, nome, preco) values (499, 'Sweet Honey BBQ Wings', 6.99);
insert into pedido (id_produto, nome, preco) values (500, 'Succulent Pulled Pork Sandwich', 3.99);
insert into pedido (id_produto, nome, preco) values (501, 'Wholesome Quinoa Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (502, 'Creamy Mushroom Risotto', 4.79);
insert into pedido (id_produto, nome, preco) values (503, 'Creamy Mushroom Risotto', 24.99);
insert into pedido (id_produto, nome, preco) values (504, 'Exotic Mango Tango Smoothie', 5.29);
insert into pedido (id_produto, nome, preco) values (505, 'Sweet Honey BBQ Wings', 3.49);
insert into pedido (id_produto, nome, preco) values (506, 'Deluxe Seafood Platter', 19.99);
insert into pedido (id_produto, nome, preco) values (507, 'Savory Garlic Shrimp Pasta', 2.79);
insert into pedido (id_produto, nome, preco) values (508, 'Creamy Mushroom Risotto', 29.99);
insert into pedido (id_produto, nome, preco) values (509, 'Succulent Pulled Pork Sandwich', 24.99);
insert into pedido (id_produto, nome, preco) values (510, 'Deluxe Seafood Platter', 199.99);
insert into pedido (id_produto, nome, preco) values (511, 'Crispy Parmesan Chicken', 2.99);
insert into pedido (id_produto, nome, preco) values (512, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (513, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (514, 'Savory Garlic Shrimp Pasta', 11.99);
insert into pedido (id_produto, nome, preco) values (515, 'Exotic Mango Tango Smoothie', 2.49);
insert into pedido (id_produto, nome, preco) values (516, 'Tangy Orange Glazed Duck', 19.99);
insert into pedido (id_produto, nome, preco) values (517, 'Mouthwatering Teriyaki Tofu Bowl', 29.99);
insert into pedido (id_produto, nome, preco) values (518, 'Sweet Honey BBQ Wings', 19.99);
insert into pedido (id_produto, nome, preco) values (519, 'Zesty Lemon Salmon', 29.99);
insert into pedido (id_produto, nome, preco) values (520, 'Decadent Chocolate Lava Cake', 8.99);
insert into pedido (id_produto, nome, preco) values (521, 'Succulent Pulled Pork Sandwich', 3.49);
insert into pedido (id_produto, nome, preco) values (522, 'Succulent Pulled Pork Sandwich', 2.29);
insert into pedido (id_produto, nome, preco) values (523, 'Mouthwatering Teriyaki Tofu Bowl', 3.99);
insert into pedido (id_produto, nome, preco) values (524, 'Refreshing Watermelon Salad', 8.99);
insert into pedido (id_produto, nome, preco) values (525, 'Sizzling BBQ Ribs', 15.99);
insert into pedido (id_produto, nome, preco) values (526, 'Tangy Orange Glazed Duck', 14.99);
insert into pedido (id_produto, nome, preco) values (527, 'Wholesome Quinoa Salad', 129.99);
insert into pedido (id_produto, nome, preco) values (528, 'Succulent Pulled Pork Sandwich', 1.99);
insert into pedido (id_produto, nome, preco) values (529, 'Homestyle Apple Pie', 2.99);
insert into pedido (id_produto, nome, preco) values (530, 'Exotic Mango Tango Smoothie', 4.99);
insert into pedido (id_produto, nome, preco) values (531, 'Spicy Jalapeno Burger', 2.19);
insert into pedido (id_produto, nome, preco) values (532, 'Flavorful Veggie Stir-Fry', 29.99);
insert into pedido (id_produto, nome, preco) values (533, 'Wholesome Quinoa Salad', 49.99);
insert into pedido (id_produto, nome, preco) values (534, 'Exotic Mango Tango Smoothie', 89.99);
insert into pedido (id_produto, nome, preco) values (535, 'Sizzling BBQ Ribs', 29.99);
insert into pedido (id_produto, nome, preco) values (536, 'Succulent Pulled Pork Sandwich', 0.99);
insert into pedido (id_produto, nome, preco) values (537, 'Decadent Chocolate Lava Cake', 8.99);
insert into pedido (id_produto, nome, preco) values (538, 'Decadent Chocolate Lava Cake', 2.49);
insert into pedido (id_produto, nome, preco) values (539, 'Exotic Mango Tango Smoothie', 3.49);
insert into pedido (id_produto, nome, preco) values (540, 'Mouthwatering Teriyaki Tofu Bowl', 2.29);
insert into pedido (id_produto, nome, preco) values (541, 'Decadent Chocolate Lava Cake', 3.99);
insert into pedido (id_produto, nome, preco) values (542, 'Sizzling BBQ Ribs', 2.49);
insert into pedido (id_produto, nome, preco) values (543, 'Sweet Honey BBQ Wings', 89.99);
insert into pedido (id_produto, nome, preco) values (544, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (545, 'Cheesy Bacon Macaroni', 1.29);
insert into pedido (id_produto, nome, preco) values (546, 'Hearty Beef Stew', 2.99);
insert into pedido (id_produto, nome, preco) values (547, 'Hearty Beef Stew', 15.99);
insert into pedido (id_produto, nome, preco) values (548, 'Decadent Chocolate Lava Cake', 89.99);
insert into pedido (id_produto, nome, preco) values (549, 'Mouthwatering Teriyaki Tofu Bowl', 5.99);
insert into pedido (id_produto, nome, preco) values (550, 'Flavorful Veggie Stir-Fry', 24.99);
insert into pedido (id_produto, nome, preco) values (551, 'Deluxe Seafood Platter', 299.99);
insert into pedido (id_produto, nome, preco) values (552, 'Flavorful Veggie Stir-Fry', 4.99);
insert into pedido (id_produto, nome, preco) values (553, 'Gourmet Truffle Fries', 19.99);
insert into pedido (id_produto, nome, preco) values (554, 'Creamy Mushroom Risotto', 3.99);
insert into pedido (id_produto, nome, preco) values (555, 'Flavorful Veggie Stir-Fry', 2.99);
insert into pedido (id_produto, nome, preco) values (556, 'Creamy Mushroom Risotto', 9.99);
insert into pedido (id_produto, nome, preco) values (557, 'Crispy Parmesan Chicken', 3.99);
insert into pedido (id_produto, nome, preco) values (558, 'Exotic Mango Tango Smoothie', 4.99);
insert into pedido (id_produto, nome, preco) values (559, 'Hearty Beef Stew', 8.99);
insert into pedido (id_produto, nome, preco) values (560, 'Tangy Orange Glazed Duck', 3.99);
insert into pedido (id_produto, nome, preco) values (561, 'Savory Garlic Shrimp Pasta', 3.59);
insert into pedido (id_produto, nome, preco) values (562, 'Sizzling BBQ Ribs', 2.49);
insert into pedido (id_produto, nome, preco) values (563, 'Creamy Mushroom Risotto', 3.49);
insert into pedido (id_produto, nome, preco) values (564, 'Savory Garlic Shrimp Pasta', 3.49);
insert into pedido (id_produto, nome, preco) values (565, 'Zesty Lemon Salmon', 1.89);
insert into pedido (id_produto, nome, preco) values (566, 'Refreshing Watermelon Salad', 5.49);
insert into pedido (id_produto, nome, preco) values (567, 'Zesty Lemon Salmon', 299.99);
insert into pedido (id_produto, nome, preco) values (568, 'Cheesy Bacon Macaroni', 39.99);
insert into pedido (id_produto, nome, preco) values (569, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (570, 'Refreshing Watermelon Salad', 89.99);
insert into pedido (id_produto, nome, preco) values (571, 'Succulent Pulled Pork Sandwich', 3.49);
insert into pedido (id_produto, nome, preco) values (572, 'Savory Garlic Shrimp Pasta', 89.99);
insert into pedido (id_produto, nome, preco) values (573, 'Sweet Honey BBQ Wings', 3.29);
insert into pedido (id_produto, nome, preco) values (574, 'Sweet Honey BBQ Wings', 49.99);
insert into pedido (id_produto, nome, preco) values (575, 'Spicy Jalapeno Burger', 299.99);
insert into pedido (id_produto, nome, preco) values (576, 'Decadent Chocolate Lava Cake', 3.49);
insert into pedido (id_produto, nome, preco) values (577, 'Hearty Beef Stew', 6.99);
insert into pedido (id_produto, nome, preco) values (578, 'Sizzling BBQ Ribs', 19.99);
insert into pedido (id_produto, nome, preco) values (579, 'Sizzling BBQ Ribs', 19.99);
insert into pedido (id_produto, nome, preco) values (580, 'Crispy Parmesan Chicken', 2.49);
insert into pedido (id_produto, nome, preco) values (581, 'Refreshing Watermelon Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (582, 'Decadent Chocolate Lava Cake', 3.99);
insert into pedido (id_produto, nome, preco) values (583, 'Cheesy Bacon Macaroni', 14.99);
insert into pedido (id_produto, nome, preco) values (584, 'Wholesome Quinoa Salad', 5.99);
insert into pedido (id_produto, nome, preco) values (585, 'Zesty Lemon Salmon', 199.99);
insert into pedido (id_produto, nome, preco) values (586, 'Creamy Mushroom Risotto', 4.99);
insert into pedido (id_produto, nome, preco) values (587, 'Mouthwatering Teriyaki Tofu Bowl', 359.99);
insert into pedido (id_produto, nome, preco) values (588, 'Decadent Chocolate Lava Cake', 99.99);
insert into pedido (id_produto, nome, preco) values (589, 'Refreshing Watermelon Salad', 16.99);
insert into pedido (id_produto, nome, preco) values (590, 'Spicy Jalapeno Burger', 29.99);
insert into pedido (id_produto, nome, preco) values (591, 'Tangy Orange Glazed Duck', 49.99);
insert into pedido (id_produto, nome, preco) values (592, 'Hearty Beef Stew', 8.99);
insert into pedido (id_produto, nome, preco) values (593, 'Gourmet Truffle Fries', 19.99);
insert into pedido (id_produto, nome, preco) values (594, 'Deluxe Seafood Platter', 1.99);
insert into pedido (id_produto, nome, preco) values (595, 'Refreshing Watermelon Salad', 59.99);
insert into pedido (id_produto, nome, preco) values (596, 'Cheesy Bacon Macaroni', 3.49);
insert into pedido (id_produto, nome, preco) values (597, 'Wholesome Quinoa Salad', 4.29);
insert into pedido (id_produto, nome, preco) values (598, 'Mouthwatering Teriyaki Tofu Bowl', 34.99);
insert into pedido (id_produto, nome, preco) values (599, 'Homestyle Apple Pie', 3.49);
insert into pedido (id_produto, nome, preco) values (600, 'Refreshing Watermelon Salad', 3.99);
insert into pedido (id_produto, nome, preco) values (601, 'Homestyle Apple Pie', 89.99);
insert into pedido (id_produto, nome, preco) values (602, 'Exotic Mango Tango Smoothie', 19.99);
insert into pedido (id_produto, nome, preco) values (603, 'Flavorful Veggie Stir-Fry', 2.49);
insert into pedido (id_produto, nome, preco) values (604, 'Hearty Beef Stew', 24.99);
insert into pedido (id_produto, nome, preco) values (605, 'Cheesy Bacon Macaroni', 3.89);
insert into pedido (id_produto, nome, preco) values (606, 'Sizzling BBQ Ribs', 39.99);
insert into pedido (id_produto, nome, preco) values (607, 'Cheesy Bacon Macaroni', 6.49);
insert into pedido (id_produto, nome, preco) values (608, 'Wholesome Quinoa Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (609, 'Decadent Chocolate Lava Cake', 24.99);
insert into pedido (id_produto, nome, preco) values (610, 'Cheesy Bacon Macaroni', 15.99);
insert into pedido (id_produto, nome, preco) values (611, 'Savory Garlic Shrimp Pasta', 3.79);
insert into pedido (id_produto, nome, preco) values (612, 'Sizzling BBQ Ribs', 19.99);
insert into pedido (id_produto, nome, preco) values (613, 'Creamy Mushroom Risotto', 9.99);
insert into pedido (id_produto, nome, preco) values (614, 'Gourmet Truffle Fries', 19.99);
insert into pedido (id_produto, nome, preco) values (615, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (616, 'Mouthwatering Teriyaki Tofu Bowl', 4.49);
insert into pedido (id_produto, nome, preco) values (617, 'Succulent Pulled Pork Sandwich', 5.29);
insert into pedido (id_produto, nome, preco) values (618, 'Zesty Lemon Salmon', 3.29);
insert into pedido (id_produto, nome, preco) values (619, 'Deluxe Seafood Platter', 3.29);
insert into pedido (id_produto, nome, preco) values (620, 'Spicy Jalapeno Burger', 44.99);
insert into pedido (id_produto, nome, preco) values (621, 'Refreshing Watermelon Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (622, 'Gourmet Truffle Fries', 89.99);
insert into pedido (id_produto, nome, preco) values (623, 'Spicy Jalapeno Burger', 34.99);
insert into pedido (id_produto, nome, preco) values (624, 'Creamy Mushroom Risotto', 2.99);
insert into pedido (id_produto, nome, preco) values (625, 'Crispy Parmesan Chicken', 3.29);
insert into pedido (id_produto, nome, preco) values (626, 'Mouthwatering Teriyaki Tofu Bowl', 7.99);
insert into pedido (id_produto, nome, preco) values (627, 'Creamy Mushroom Risotto', 14.99);
insert into pedido (id_produto, nome, preco) values (628, 'Homestyle Apple Pie', 3.29);
insert into pedido (id_produto, nome, preco) values (629, 'Gourmet Truffle Fries', 12.99);
insert into pedido (id_produto, nome, preco) values (630, 'Homestyle Apple Pie', 4.99);
insert into pedido (id_produto, nome, preco) values (631, 'Zesty Lemon Salmon', 5.79);
insert into pedido (id_produto, nome, preco) values (632, 'Zesty Lemon Salmon', 8.99);
insert into pedido (id_produto, nome, preco) values (633, 'Savory Garlic Shrimp Pasta', 39.99);
insert into pedido (id_produto, nome, preco) values (634, 'Refreshing Watermelon Salad', 39.99);
insert into pedido (id_produto, nome, preco) values (635, 'Zesty Lemon Salmon', 4.99);
insert into pedido (id_produto, nome, preco) values (636, 'Creamy Mushroom Risotto', 79.99);
insert into pedido (id_produto, nome, preco) values (637, 'Flavorful Veggie Stir-Fry', 3.49);
insert into pedido (id_produto, nome, preco) values (638, 'Decadent Chocolate Lava Cake', 2.99);
insert into pedido (id_produto, nome, preco) values (639, 'Decadent Chocolate Lava Cake', 39.99);
insert into pedido (id_produto, nome, preco) values (640, 'Tangy Orange Glazed Duck', 44.99);
insert into pedido (id_produto, nome, preco) values (641, 'Wholesome Quinoa Salad', 2.49);
insert into pedido (id_produto, nome, preco) values (642, 'Wholesome Quinoa Salad', 6.99);
insert into pedido (id_produto, nome, preco) values (643, 'Savory Garlic Shrimp Pasta', 1.99);
insert into pedido (id_produto, nome, preco) values (644, 'Savory Garlic Shrimp Pasta', 1.89);
insert into pedido (id_produto, nome, preco) values (645, 'Savory Garlic Shrimp Pasta', 29.99);
insert into pedido (id_produto, nome, preco) values (646, 'Hearty Beef Stew', 99.99);
insert into pedido (id_produto, nome, preco) values (647, 'Deluxe Seafood Platter', 2.99);
insert into pedido (id_produto, nome, preco) values (648, 'Succulent Pulled Pork Sandwich', 49.99);
insert into pedido (id_produto, nome, preco) values (649, 'Spicy Jalapeno Burger', 29.99);
insert into pedido (id_produto, nome, preco) values (650, 'Decadent Chocolate Lava Cake', 2.49);
insert into pedido (id_produto, nome, preco) values (651, 'Homestyle Apple Pie', 24.99);
insert into pedido (id_produto, nome, preco) values (652, 'Sizzling BBQ Ribs', 19.99);
insert into pedido (id_produto, nome, preco) values (653, 'Zesty Lemon Salmon', 9.99);
insert into pedido (id_produto, nome, preco) values (654, 'Decadent Chocolate Lava Cake', 3.99);
insert into pedido (id_produto, nome, preco) values (655, 'Spicy Jalapeno Burger', 5.99);
insert into pedido (id_produto, nome, preco) values (656, 'Wholesome Quinoa Salad', 69.99);
insert into pedido (id_produto, nome, preco) values (657, 'Creamy Mushroom Risotto', 24.99);
insert into pedido (id_produto, nome, preco) values (658, 'Zesty Lemon Salmon', 45.99);
insert into pedido (id_produto, nome, preco) values (659, 'Creamy Mushroom Risotto', 4.99);
insert into pedido (id_produto, nome, preco) values (660, 'Exotic Mango Tango Smoothie', 10.99);
insert into pedido (id_produto, nome, preco) values (661, 'Sweet Honey BBQ Wings', 6.49);
insert into pedido (id_produto, nome, preco) values (662, 'Flavorful Veggie Stir-Fry', 49.99);
insert into pedido (id_produto, nome, preco) values (663, 'Hearty Beef Stew', 2.99);
insert into pedido (id_produto, nome, preco) values (664, 'Tangy Orange Glazed Duck', 29.99);
insert into pedido (id_produto, nome, preco) values (665, 'Cheesy Bacon Macaroni', 7.99);
insert into pedido (id_produto, nome, preco) values (666, 'Flavorful Veggie Stir-Fry', 22.99);
insert into pedido (id_produto, nome, preco) values (667, 'Flavorful Veggie Stir-Fry', 14.99);
insert into pedido (id_produto, nome, preco) values (668, 'Tangy Orange Glazed Duck', 24.99);
insert into pedido (id_produto, nome, preco) values (669, 'Sweet Honey BBQ Wings', 49.99);
insert into pedido (id_produto, nome, preco) values (670, 'Decadent Chocolate Lava Cake', 3.29);
insert into pedido (id_produto, nome, preco) values (671, 'Succulent Pulled Pork Sandwich', 2.99);
insert into pedido (id_produto, nome, preco) values (672, 'Savory Garlic Shrimp Pasta', 5.49);
insert into pedido (id_produto, nome, preco) values (673, 'Exotic Mango Tango Smoothie', 34.99);
insert into pedido (id_produto, nome, preco) values (674, 'Tangy Orange Glazed Duck', 59.99);
insert into pedido (id_produto, nome, preco) values (675, 'Exotic Mango Tango Smoothie', 24.99);
insert into pedido (id_produto, nome, preco) values (676, 'Crispy Parmesan Chicken', 34.99);
insert into pedido (id_produto, nome, preco) values (677, 'Refreshing Watermelon Salad', 4.99);
insert into pedido (id_produto, nome, preco) values (678, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (679, 'Crispy Parmesan Chicken', 49.99);
insert into pedido (id_produto, nome, preco) values (680, 'Homestyle Apple Pie', 3.49);
insert into pedido (id_produto, nome, preco) values (681, 'Zesty Lemon Salmon', 3.59);
insert into pedido (id_produto, nome, preco) values (682, 'Savory Garlic Shrimp Pasta', 18.99);
insert into pedido (id_produto, nome, preco) values (683, 'Decadent Chocolate Lava Cake', 4.99);
insert into pedido (id_produto, nome, preco) values (684, 'Homestyle Apple Pie', 34.99);
insert into pedido (id_produto, nome, preco) values (685, 'Tangy Orange Glazed Duck', 4.59);
insert into pedido (id_produto, nome, preco) values (686, 'Cheesy Bacon Macaroni', 39.99);
insert into pedido (id_produto, nome, preco) values (687, 'Homestyle Apple Pie', 3.99);
insert into pedido (id_produto, nome, preco) values (688, 'Gourmet Truffle Fries', 2.49);
insert into pedido (id_produto, nome, preco) values (689, 'Sizzling BBQ Ribs', 29.99);
insert into pedido (id_produto, nome, preco) values (690, 'Gourmet Truffle Fries', 49.99);
insert into pedido (id_produto, nome, preco) values (691, 'Savory Garlic Shrimp Pasta', 2.99);
insert into pedido (id_produto, nome, preco) values (692, 'Succulent Pulled Pork Sandwich', 14.99);
insert into pedido (id_produto, nome, preco) values (693, 'Exotic Mango Tango Smoothie', 49.99);
insert into pedido (id_produto, nome, preco) values (694, 'Gourmet Truffle Fries', 39.99);
insert into pedido (id_produto, nome, preco) values (695, 'Savory Garlic Shrimp Pasta', 14.99);
insert into pedido (id_produto, nome, preco) values (696, 'Zesty Lemon Salmon', 39.99);
insert into pedido (id_produto, nome, preco) values (697, 'Deluxe Seafood Platter', 12.99);
insert into pedido (id_produto, nome, preco) values (698, 'Gourmet Truffle Fries', 3.99);
insert into pedido (id_produto, nome, preco) values (699, 'Deluxe Seafood Platter', 1.99);
insert into pedido (id_produto, nome, preco) values (700, 'Refreshing Watermelon Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (701, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (702, 'Refreshing Watermelon Salad', 1.29);
insert into pedido (id_produto, nome, preco) values (703, 'Exotic Mango Tango Smoothie', 5.99);
insert into pedido (id_produto, nome, preco) values (704, 'Homestyle Apple Pie', 3.59);
insert into pedido (id_produto, nome, preco) values (705, 'Wholesome Quinoa Salad', 12.99);
insert into pedido (id_produto, nome, preco) values (706, 'Flavorful Veggie Stir-Fry', 2.99);
insert into pedido (id_produto, nome, preco) values (707, 'Crispy Parmesan Chicken', 2.29);
insert into pedido (id_produto, nome, preco) values (708, 'Creamy Mushroom Risotto', 39.99);
insert into pedido (id_produto, nome, preco) values (709, 'Homestyle Apple Pie', 54.99);
insert into pedido (id_produto, nome, preco) values (710, 'Succulent Pulled Pork Sandwich', 12.99);
insert into pedido (id_produto, nome, preco) values (711, 'Creamy Mushroom Risotto', 58.99);
insert into pedido (id_produto, nome, preco) values (712, 'Creamy Mushroom Risotto', 6.49);
insert into pedido (id_produto, nome, preco) values (713, 'Exotic Mango Tango Smoothie', 4.49);
insert into pedido (id_produto, nome, preco) values (714, 'Savory Garlic Shrimp Pasta', 3.79);
insert into pedido (id_produto, nome, preco) values (715, 'Spicy Jalapeno Burger', 29.99);
insert into pedido (id_produto, nome, preco) values (716, 'Sweet Honey BBQ Wings', 5.49);
insert into pedido (id_produto, nome, preco) values (717, 'Hearty Beef Stew', 2.39);
insert into pedido (id_produto, nome, preco) values (718, 'Zesty Lemon Salmon', 45);
insert into pedido (id_produto, nome, preco) values (719, 'Crispy Parmesan Chicken', 3.49);
insert into pedido (id_produto, nome, preco) values (720, 'Deluxe Seafood Platter', 2.49);
insert into pedido (id_produto, nome, preco) values (721, 'Deluxe Seafood Platter', 15.99);
insert into pedido (id_produto, nome, preco) values (722, 'Succulent Pulled Pork Sandwich', 3.99);
insert into pedido (id_produto, nome, preco) values (723, 'Refreshing Watermelon Salad', 89.99);
insert into pedido (id_produto, nome, preco) values (724, 'Crispy Parmesan Chicken', 1.99);
insert into pedido (id_produto, nome, preco) values (725, 'Homestyle Apple Pie', 3.59);
insert into pedido (id_produto, nome, preco) values (726, 'Tangy Orange Glazed Duck', 1.99);
insert into pedido (id_produto, nome, preco) values (727, 'Mouthwatering Teriyaki Tofu Bowl', 10.99);
insert into pedido (id_produto, nome, preco) values (728, 'Spicy Jalapeno Burger', 12.99);
insert into pedido (id_produto, nome, preco) values (729, 'Gourmet Truffle Fries', 7.49);
insert into pedido (id_produto, nome, preco) values (730, 'Spicy Jalapeno Burger', 2.99);
insert into pedido (id_produto, nome, preco) values (731, 'Deluxe Seafood Platter', 15.49);
insert into pedido (id_produto, nome, preco) values (732, 'Mouthwatering Teriyaki Tofu Bowl', 89.99);
insert into pedido (id_produto, nome, preco) values (733, 'Hearty Beef Stew', 5.49);
insert into pedido (id_produto, nome, preco) values (734, 'Spicy Jalapeno Burger', 5.49);
insert into pedido (id_produto, nome, preco) values (735, 'Wholesome Quinoa Salad', 0.99);
insert into pedido (id_produto, nome, preco) values (736, 'Gourmet Truffle Fries', 199.99);
insert into pedido (id_produto, nome, preco) values (737, 'Deluxe Seafood Platter', 16.99);
insert into pedido (id_produto, nome, preco) values (738, 'Succulent Pulled Pork Sandwich', 4.29);
insert into pedido (id_produto, nome, preco) values (739, 'Sizzling BBQ Ribs', 3.49);
insert into pedido (id_produto, nome, preco) values (740, 'Gourmet Truffle Fries', 3.59);
insert into pedido (id_produto, nome, preco) values (741, 'Crispy Parmesan Chicken', 4.99);
insert into pedido (id_produto, nome, preco) values (742, 'Exotic Mango Tango Smoothie', 99.99);
insert into pedido (id_produto, nome, preco) values (743, 'Gourmet Truffle Fries', 3.29);
insert into pedido (id_produto, nome, preco) values (744, 'Gourmet Truffle Fries', 8.49);
insert into pedido (id_produto, nome, preco) values (745, 'Gourmet Truffle Fries', 39.99);
insert into pedido (id_produto, nome, preco) values (746, 'Tangy Orange Glazed Duck', 3.99);
insert into pedido (id_produto, nome, preco) values (747, 'Wholesome Quinoa Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (748, 'Cheesy Bacon Macaroni', 149.99);
insert into pedido (id_produto, nome, preco) values (749, 'Homestyle Apple Pie', 7.99);
insert into pedido (id_produto, nome, preco) values (750, 'Zesty Lemon Salmon', 99.99);
insert into pedido (id_produto, nome, preco) values (751, 'Flavorful Veggie Stir-Fry', 15.99);
insert into pedido (id_produto, nome, preco) values (752, 'Crispy Parmesan Chicken', 9.99);
insert into pedido (id_produto, nome, preco) values (753, 'Tangy Orange Glazed Duck', 4.49);
insert into pedido (id_produto, nome, preco) values (754, 'Wholesome Quinoa Salad', 5.99);
insert into pedido (id_produto, nome, preco) values (755, 'Creamy Mushroom Risotto', 89.99);
insert into pedido (id_produto, nome, preco) values (756, 'Decadent Chocolate Lava Cake', 49.99);
insert into pedido (id_produto, nome, preco) values (757, 'Exotic Mango Tango Smoothie', 9.99);
insert into pedido (id_produto, nome, preco) values (758, 'Zesty Lemon Salmon', 24.99);
insert into pedido (id_produto, nome, preco) values (759, 'Sizzling BBQ Ribs', 4.29);
insert into pedido (id_produto, nome, preco) values (760, 'Creamy Mushroom Risotto', 5.49);
insert into pedido (id_produto, nome, preco) values (761, 'Cheesy Bacon Macaroni', 89.99);
insert into pedido (id_produto, nome, preco) values (762, 'Wholesome Quinoa Salad', 2.49);
insert into pedido (id_produto, nome, preco) values (763, 'Sizzling BBQ Ribs', 4.49);
insert into pedido (id_produto, nome, preco) values (764, 'Succulent Pulled Pork Sandwich', 6.49);
insert into pedido (id_produto, nome, preco) values (765, 'Refreshing Watermelon Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (766, 'Exotic Mango Tango Smoothie', 15.99);
insert into pedido (id_produto, nome, preco) values (767, 'Gourmet Truffle Fries', 129.99);
insert into pedido (id_produto, nome, preco) values (768, 'Spicy Jalapeno Burger', 4.99);
insert into pedido (id_produto, nome, preco) values (769, 'Spicy Jalapeno Burger', 9.99);
insert into pedido (id_produto, nome, preco) values (770, 'Zesty Lemon Salmon', 2.99);
insert into pedido (id_produto, nome, preco) values (771, 'Mouthwatering Teriyaki Tofu Bowl', 49.99);
insert into pedido (id_produto, nome, preco) values (772, 'Flavorful Veggie Stir-Fry', 3.99);
insert into pedido (id_produto, nome, preco) values (773, 'Wholesome Quinoa Salad', 6.99);
insert into pedido (id_produto, nome, preco) values (774, 'Tangy Orange Glazed Duck', 5.99);
insert into pedido (id_produto, nome, preco) values (775, 'Gourmet Truffle Fries', 1.79);
insert into pedido (id_produto, nome, preco) values (776, 'Hearty Beef Stew', 79.99);
insert into pedido (id_produto, nome, preco) values (777, 'Exotic Mango Tango Smoothie', 3.99);
insert into pedido (id_produto, nome, preco) values (778, 'Mouthwatering Teriyaki Tofu Bowl', 34.99);
insert into pedido (id_produto, nome, preco) values (779, 'Exotic Mango Tango Smoothie', 2.99);
insert into pedido (id_produto, nome, preco) values (780, 'Savory Garlic Shrimp Pasta', 2.39);
insert into pedido (id_produto, nome, preco) values (781, 'Gourmet Truffle Fries', 49.99);
insert into pedido (id_produto, nome, preco) values (782, 'Sizzling BBQ Ribs', 39.99);
insert into pedido (id_produto, nome, preco) values (783, 'Wholesome Quinoa Salad', 5.99);
insert into pedido (id_produto, nome, preco) values (784, 'Spicy Jalapeno Burger', 14.99);
insert into pedido (id_produto, nome, preco) values (785, 'Sweet Honey BBQ Wings', 18.99);
insert into pedido (id_produto, nome, preco) values (786, 'Zesty Lemon Salmon', 3.99);
insert into pedido (id_produto, nome, preco) values (787, 'Tangy Orange Glazed Duck', 29.99);
insert into pedido (id_produto, nome, preco) values (788, 'Creamy Mushroom Risotto', 12.99);
insert into pedido (id_produto, nome, preco) values (789, 'Mouthwatering Teriyaki Tofu Bowl', 22.99);
insert into pedido (id_produto, nome, preco) values (790, 'Decadent Chocolate Lava Cake', 4.49);
insert into pedido (id_produto, nome, preco) values (791, 'Succulent Pulled Pork Sandwich', 2.99);
insert into pedido (id_produto, nome, preco) values (792, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (793, 'Sizzling BBQ Ribs', 3.99);
insert into pedido (id_produto, nome, preco) values (794, 'Mouthwatering Teriyaki Tofu Bowl', 89.99);
insert into pedido (id_produto, nome, preco) values (795, 'Sizzling BBQ Ribs', 18.99);
insert into pedido (id_produto, nome, preco) values (796, 'Tangy Orange Glazed Duck', 3.99);
insert into pedido (id_produto, nome, preco) values (797, 'Mouthwatering Teriyaki Tofu Bowl', 39.99);
insert into pedido (id_produto, nome, preco) values (798, 'Deluxe Seafood Platter', 24.99);
insert into pedido (id_produto, nome, preco) values (799, 'Deluxe Seafood Platter', 49.99);
insert into pedido (id_produto, nome, preco) values (800, 'Succulent Pulled Pork Sandwich', 2.99);
insert into pedido (id_produto, nome, preco) values (801, 'Savory Garlic Shrimp Pasta', 4.99);
insert into pedido (id_produto, nome, preco) values (802, 'Refreshing Watermelon Salad', 4.29);
insert into pedido (id_produto, nome, preco) values (803, 'Succulent Pulled Pork Sandwich', 14.99);
insert into pedido (id_produto, nome, preco) values (804, 'Sweet Honey BBQ Wings', 3.29);
insert into pedido (id_produto, nome, preco) values (805, 'Savory Garlic Shrimp Pasta', 3.29);
insert into pedido (id_produto, nome, preco) values (806, 'Flavorful Veggie Stir-Fry', 2.49);
insert into pedido (id_produto, nome, preco) values (807, 'Exotic Mango Tango Smoothie', 59.99);
insert into pedido (id_produto, nome, preco) values (808, 'Exotic Mango Tango Smoothie', 15.99);
insert into pedido (id_produto, nome, preco) values (809, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (810, 'Refreshing Watermelon Salad', 19.99);
insert into pedido (id_produto, nome, preco) values (811, 'Tangy Orange Glazed Duck', 8.99);
insert into pedido (id_produto, nome, preco) values (812, 'Spicy Jalapeno Burger', 19.99);
insert into pedido (id_produto, nome, preco) values (813, 'Flavorful Veggie Stir-Fry', 3.79);
insert into pedido (id_produto, nome, preco) values (814, 'Flavorful Veggie Stir-Fry', 4.49);
insert into pedido (id_produto, nome, preco) values (815, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (816, 'Cheesy Bacon Macaroni', 29.99);
insert into pedido (id_produto, nome, preco) values (817, 'Deluxe Seafood Platter', 24.99);
insert into pedido (id_produto, nome, preco) values (818, 'Tangy Orange Glazed Duck', 58.99);
insert into pedido (id_produto, nome, preco) values (819, 'Creamy Mushroom Risotto', 0.99);
insert into pedido (id_produto, nome, preco) values (820, 'Deluxe Seafood Platter', 12.99);
insert into pedido (id_produto, nome, preco) values (821, 'Savory Garlic Shrimp Pasta', 2.79);
insert into pedido (id_produto, nome, preco) values (822, 'Crispy Parmesan Chicken', 8.99);
insert into pedido (id_produto, nome, preco) values (823, 'Crispy Parmesan Chicken', 4.99);
insert into pedido (id_produto, nome, preco) values (824, 'Sweet Honey BBQ Wings', 4.99);
insert into pedido (id_produto, nome, preco) values (825, 'Wholesome Quinoa Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (826, 'Crispy Parmesan Chicken', 59.99);
insert into pedido (id_produto, nome, preco) values (827, 'Homestyle Apple Pie', 2.49);
insert into pedido (id_produto, nome, preco) values (828, 'Savory Garlic Shrimp Pasta', 49.99);
insert into pedido (id_produto, nome, preco) values (829, 'Spicy Jalapeno Burger', 29.99);
insert into pedido (id_produto, nome, preco) values (830, 'Zesty Lemon Salmon', 4.29);
insert into pedido (id_produto, nome, preco) values (831, 'Zesty Lemon Salmon', 39.99);
insert into pedido (id_produto, nome, preco) values (832, 'Refreshing Watermelon Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (833, 'Crispy Parmesan Chicken', 4.29);
insert into pedido (id_produto, nome, preco) values (834, 'Wholesome Quinoa Salad', 2.69);
insert into pedido (id_produto, nome, preco) values (835, 'Exotic Mango Tango Smoothie', 2.49);
insert into pedido (id_produto, nome, preco) values (836, 'Succulent Pulled Pork Sandwich', 19.99);
insert into pedido (id_produto, nome, preco) values (837, 'Zesty Lemon Salmon', 49.99);
insert into pedido (id_produto, nome, preco) values (838, 'Homestyle Apple Pie', 9.99);
insert into pedido (id_produto, nome, preco) values (839, 'Flavorful Veggie Stir-Fry', 1.79);
insert into pedido (id_produto, nome, preco) values (840, 'Sizzling BBQ Ribs', 1.99);
insert into pedido (id_produto, nome, preco) values (841, 'Flavorful Veggie Stir-Fry', 24.99);
insert into pedido (id_produto, nome, preco) values (842, 'Wholesome Quinoa Salad', 3.29);
insert into pedido (id_produto, nome, preco) values (843, 'Flavorful Veggie Stir-Fry', 39.99);
insert into pedido (id_produto, nome, preco) values (844, 'Flavorful Veggie Stir-Fry', 3.79);
insert into pedido (id_produto, nome, preco) values (845, 'Savory Garlic Shrimp Pasta', 3.99);
insert into pedido (id_produto, nome, preco) values (846, 'Decadent Chocolate Lava Cake', 39.99);
insert into pedido (id_produto, nome, preco) values (847, 'Zesty Lemon Salmon', 22.99);
insert into pedido (id_produto, nome, preco) values (848, 'Sweet Honey BBQ Wings', 34.99);
insert into pedido (id_produto, nome, preco) values (849, 'Flavorful Veggie Stir-Fry', 99.99);
insert into pedido (id_produto, nome, preco) values (850, 'Crispy Parmesan Chicken', 14.99);
insert into pedido (id_produto, nome, preco) values (851, 'Flavorful Veggie Stir-Fry', 3.49);
insert into pedido (id_produto, nome, preco) values (852, 'Decadent Chocolate Lava Cake', 39.99);
insert into pedido (id_produto, nome, preco) values (853, 'Cheesy Bacon Macaroni', 24.99);
insert into pedido (id_produto, nome, preco) values (854, 'Savory Garlic Shrimp Pasta', 22.99);
insert into pedido (id_produto, nome, preco) values (855, 'Spicy Jalapeno Burger', 2.39);
insert into pedido (id_produto, nome, preco) values (856, 'Tangy Orange Glazed Duck', 22.99);
insert into pedido (id_produto, nome, preco) values (857, 'Decadent Chocolate Lava Cake', 34.99);
insert into pedido (id_produto, nome, preco) values (858, 'Creamy Mushroom Risotto', 39.99);
insert into pedido (id_produto, nome, preco) values (859, 'Crispy Parmesan Chicken', 29.99);
insert into pedido (id_produto, nome, preco) values (860, 'Gourmet Truffle Fries', 6.99);
insert into pedido (id_produto, nome, preco) values (861, 'Cheesy Bacon Macaroni', 29.99);
insert into pedido (id_produto, nome, preco) values (862, 'Zesty Lemon Salmon', 7.49);
insert into pedido (id_produto, nome, preco) values (863, 'Refreshing Watermelon Salad', 22.99);
insert into pedido (id_produto, nome, preco) values (864, 'Mouthwatering Teriyaki Tofu Bowl', 49.99);
insert into pedido (id_produto, nome, preco) values (865, 'Crispy Parmesan Chicken', 15.99);
insert into pedido (id_produto, nome, preco) values (866, 'Flavorful Veggie Stir-Fry', 39.99);
insert into pedido (id_produto, nome, preco) values (867, 'Sweet Honey BBQ Wings', 4.29);
insert into pedido (id_produto, nome, preco) values (868, 'Decadent Chocolate Lava Cake', 2.99);
insert into pedido (id_produto, nome, preco) values (869, 'Exotic Mango Tango Smoothie', 10.99);
insert into pedido (id_produto, nome, preco) values (870, 'Mouthwatering Teriyaki Tofu Bowl', 8.99);
insert into pedido (id_produto, nome, preco) values (871, 'Sizzling BBQ Ribs', 34.99);
insert into pedido (id_produto, nome, preco) values (872, 'Hearty Beef Stew', 3.19);
insert into pedido (id_produto, nome, preco) values (873, 'Hearty Beef Stew', 5.49);
insert into pedido (id_produto, nome, preco) values (874, 'Tangy Orange Glazed Duck', 299.99);
insert into pedido (id_produto, nome, preco) values (875, 'Homestyle Apple Pie', 59.99);
insert into pedido (id_produto, nome, preco) values (876, 'Hearty Beef Stew', 8.99);
insert into pedido (id_produto, nome, preco) values (877, 'Zesty Lemon Salmon', 24.99);
insert into pedido (id_produto, nome, preco) values (878, 'Decadent Chocolate Lava Cake', 1.29);
insert into pedido (id_produto, nome, preco) values (879, 'Exotic Mango Tango Smoothie', 5.99);
insert into pedido (id_produto, nome, preco) values (880, 'Deluxe Seafood Platter', 6.99);
insert into pedido (id_produto, nome, preco) values (881, 'Exotic Mango Tango Smoothie', 29.99);
insert into pedido (id_produto, nome, preco) values (882, 'Mouthwatering Teriyaki Tofu Bowl', 1.99);
insert into pedido (id_produto, nome, preco) values (883, 'Sweet Honey BBQ Wings', 7.99);
insert into pedido (id_produto, nome, preco) values (884, 'Savory Garlic Shrimp Pasta', 49.99);
insert into pedido (id_produto, nome, preco) values (885, 'Sweet Honey BBQ Wings', 4.29);
insert into pedido (id_produto, nome, preco) values (886, 'Wholesome Quinoa Salad', 29.99);
insert into pedido (id_produto, nome, preco) values (887, 'Flavorful Veggie Stir-Fry', 3.79);
insert into pedido (id_produto, nome, preco) values (888, 'Crispy Parmesan Chicken', 3.29);
insert into pedido (id_produto, nome, preco) values (889, 'Decadent Chocolate Lava Cake', 24.99);
insert into pedido (id_produto, nome, preco) values (890, 'Homestyle Apple Pie', 49.99);
insert into pedido (id_produto, nome, preco) values (891, 'Decadent Chocolate Lava Cake', 59.99);
insert into pedido (id_produto, nome, preco) values (892, 'Spicy Jalapeno Burger', 2.99);
insert into pedido (id_produto, nome, preco) values (893, 'Mouthwatering Teriyaki Tofu Bowl', 5.49);
insert into pedido (id_produto, nome, preco) values (894, 'Decadent Chocolate Lava Cake', 24.99);
insert into pedido (id_produto, nome, preco) values (895, 'Spicy Jalapeno Burger', 3.29);
insert into pedido (id_produto, nome, preco) values (896, 'Wholesome Quinoa Salad', 19.99);
insert into pedido (id_produto, nome, preco) values (897, 'Gourmet Truffle Fries', 2.99);
insert into pedido (id_produto, nome, preco) values (898, 'Homestyle Apple Pie', 10.99);
insert into pedido (id_produto, nome, preco) values (899, 'Sizzling BBQ Ribs', 54.99);
insert into pedido (id_produto, nome, preco) values (900, 'Wholesome Quinoa Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (901, 'Tangy Orange Glazed Duck', 8.99);
insert into pedido (id_produto, nome, preco) values (902, 'Crispy Parmesan Chicken', 12.99);
insert into pedido (id_produto, nome, preco) values (903, 'Cheesy Bacon Macaroni', 6.29);
insert into pedido (id_produto, nome, preco) values (904, 'Tangy Orange Glazed Duck', 34.99);
insert into pedido (id_produto, nome, preco) values (905, 'Refreshing Watermelon Salad', 149.99);
insert into pedido (id_produto, nome, preco) values (906, 'Sweet Honey BBQ Wings', 1.99);
insert into pedido (id_produto, nome, preco) values (907, 'Zesty Lemon Salmon', 19.99);
insert into pedido (id_produto, nome, preco) values (908, 'Zesty Lemon Salmon', 15.99);
insert into pedido (id_produto, nome, preco) values (909, 'Wholesome Quinoa Salad', 24.99);
insert into pedido (id_produto, nome, preco) values (910, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (911, 'Spicy Jalapeno Burger', 12.99);
insert into pedido (id_produto, nome, preco) values (912, 'Wholesome Quinoa Salad', 5.99);
insert into pedido (id_produto, nome, preco) values (913, 'Crispy Parmesan Chicken', 4.29);
insert into pedido (id_produto, nome, preco) values (914, 'Wholesome Quinoa Salad', 49.99);
insert into pedido (id_produto, nome, preco) values (915, 'Gourmet Truffle Fries', 16.99);
insert into pedido (id_produto, nome, preco) values (916, 'Hearty Beef Stew', 3.29);
insert into pedido (id_produto, nome, preco) values (917, 'Exotic Mango Tango Smoothie', 1.99);
insert into pedido (id_produto, nome, preco) values (918, 'Homestyle Apple Pie', 3.79);
insert into pedido (id_produto, nome, preco) values (919, 'Sweet Honey BBQ Wings', 4.99);
insert into pedido (id_produto, nome, preco) values (920, 'Zesty Lemon Salmon', 2.99);
insert into pedido (id_produto, nome, preco) values (921, 'Sizzling BBQ Ribs', 4.99);
insert into pedido (id_produto, nome, preco) values (922, 'Mouthwatering Teriyaki Tofu Bowl', 349.99);
insert into pedido (id_produto, nome, preco) values (923, 'Spicy Jalapeno Burger', 14.99);
insert into pedido (id_produto, nome, preco) values (924, 'Crispy Parmesan Chicken', 1.79);
insert into pedido (id_produto, nome, preco) values (925, 'Homestyle Apple Pie', 2.79);
insert into pedido (id_produto, nome, preco) values (926, 'Tangy Orange Glazed Duck', 35.99);
insert into pedido (id_produto, nome, preco) values (927, 'Flavorful Veggie Stir-Fry', 2.29);
insert into pedido (id_produto, nome, preco) values (928, 'Exotic Mango Tango Smoothie', 2.29);
insert into pedido (id_produto, nome, preco) values (929, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (930, 'Refreshing Watermelon Salad', 34.99);
insert into pedido (id_produto, nome, preco) values (931, 'Homestyle Apple Pie', 59.99);
insert into pedido (id_produto, nome, preco) values (932, 'Decadent Chocolate Lava Cake', 4.89);
insert into pedido (id_produto, nome, preco) values (933, 'Cheesy Bacon Macaroni', 199);
insert into pedido (id_produto, nome, preco) values (934, 'Crispy Parmesan Chicken', 199.99);
insert into pedido (id_produto, nome, preco) values (935, 'Cheesy Bacon Macaroni', 49.99);
insert into pedido (id_produto, nome, preco) values (936, 'Crispy Parmesan Chicken', 2.49);
insert into pedido (id_produto, nome, preco) values (937, 'Succulent Pulled Pork Sandwich', 8.99);
insert into pedido (id_produto, nome, preco) values (938, 'Cheesy Bacon Macaroni', 5.99);
insert into pedido (id_produto, nome, preco) values (939, 'Creamy Mushroom Risotto', 5.99);
insert into pedido (id_produto, nome, preco) values (940, 'Hearty Beef Stew', 39.99);
insert into pedido (id_produto, nome, preco) values (941, 'Mouthwatering Teriyaki Tofu Bowl', 1.99);
insert into pedido (id_produto, nome, preco) values (942, 'Mouthwatering Teriyaki Tofu Bowl', 49.99);
insert into pedido (id_produto, nome, preco) values (943, 'Cheesy Bacon Macaroni', 12.99);
insert into pedido (id_produto, nome, preco) values (944, 'Zesty Lemon Salmon', 7.49);
insert into pedido (id_produto, nome, preco) values (945, 'Decadent Chocolate Lava Cake', 15.99);
insert into pedido (id_produto, nome, preco) values (946, 'Sweet Honey BBQ Wings', 44.99);
insert into pedido (id_produto, nome, preco) values (947, 'Gourmet Truffle Fries', 0.79);
insert into pedido (id_produto, nome, preco) values (948, 'Tangy Orange Glazed Duck', 29.99);
insert into pedido (id_produto, nome, preco) values (949, 'Deluxe Seafood Platter', 3.49);
insert into pedido (id_produto, nome, preco) values (950, 'Deluxe Seafood Platter', 2.99);
insert into pedido (id_produto, nome, preco) values (951, 'Homestyle Apple Pie', 24.99);
insert into pedido (id_produto, nome, preco) values (952, 'Sweet Honey BBQ Wings', 79.99);
insert into pedido (id_produto, nome, preco) values (953, 'Spicy Jalapeno Burger', 59.99);
insert into pedido (id_produto, nome, preco) values (954, 'Succulent Pulled Pork Sandwich', 14.99);
insert into pedido (id_produto, nome, preco) values (955, 'Refreshing Watermelon Salad', 15.99);
insert into pedido (id_produto, nome, preco) values (956, 'Zesty Lemon Salmon', 4.99);
insert into pedido (id_produto, nome, preco) values (957, 'Creamy Mushroom Risotto', 5.49);
insert into pedido (id_produto, nome, preco) values (958, 'Flavorful Veggie Stir-Fry', 4.29);
insert into pedido (id_produto, nome, preco) values (959, 'Cheesy Bacon Macaroni', 3.49);
insert into pedido (id_produto, nome, preco) values (960, 'Flavorful Veggie Stir-Fry', 79.99);
insert into pedido (id_produto, nome, preco) values (961, 'Savory Garlic Shrimp Pasta', 32.99);
insert into pedido (id_produto, nome, preco) values (962, 'Gourmet Truffle Fries', 2.49);
insert into pedido (id_produto, nome, preco) values (963, 'Gourmet Truffle Fries', 2.79);
insert into pedido (id_produto, nome, preco) values (964, 'Refreshing Watermelon Salad', 14.99);
insert into pedido (id_produto, nome, preco) values (965, 'Spicy Jalapeno Burger', 8.49);
insert into pedido (id_produto, nome, preco) values (966, 'Tangy Orange Glazed Duck', 199.99);
insert into pedido (id_produto, nome, preco) values (967, 'Zesty Lemon Salmon', 59.99);
insert into pedido (id_produto, nome, preco) values (968, 'Crispy Parmesan Chicken', 4.99);
insert into pedido (id_produto, nome, preco) values (969, 'Crispy Parmesan Chicken', 49.99);
insert into pedido (id_produto, nome, preco) values (970, 'Tangy Orange Glazed Duck', 12.99);
insert into pedido (id_produto, nome, preco) values (971, 'Decadent Chocolate Lava Cake', 9.99);
insert into pedido (id_produto, nome, preco) values (972, 'Succulent Pulled Pork Sandwich', 49.99);
insert into pedido (id_produto, nome, preco) values (973, 'Savory Garlic Shrimp Pasta', 39.99);
insert into pedido (id_produto, nome, preco) values (974, 'Zesty Lemon Salmon', 4.09);
insert into pedido (id_produto, nome, preco) values (975, 'Spicy Jalapeno Burger', 45.99);
insert into pedido (id_produto, nome, preco) values (976, 'Hearty Beef Stew', 3.99);
insert into pedido (id_produto, nome, preco) values (977, 'Exotic Mango Tango Smoothie', 79.99);
insert into pedido (id_produto, nome, preco) values (978, 'Sizzling BBQ Ribs', 3.29);
insert into pedido (id_produto, nome, preco) values (979, 'Spicy Jalapeno Burger', 39.99);
insert into pedido (id_produto, nome, preco) values (980, 'Refreshing Watermelon Salad', 4.29);
insert into pedido (id_produto, nome, preco) values (981, 'Tangy Orange Glazed Duck', 18.99);
insert into pedido (id_produto, nome, preco) values (982, 'Hearty Beef Stew', 1.99);
insert into pedido (id_produto, nome, preco) values (983, 'Exotic Mango Tango Smoothie', 27.99);
insert into pedido (id_produto, nome, preco) values (984, 'Crispy Parmesan Chicken', 12.99);
insert into pedido (id_produto, nome, preco) values (985, 'Creamy Mushroom Risotto', 4.89);
insert into pedido (id_produto, nome, preco) values (986, 'Decadent Chocolate Lava Cake', 14.99);
insert into pedido (id_produto, nome, preco) values (987, 'Crispy Parmesan Chicken', 9.99);
insert into pedido (id_produto, nome, preco) values (988, 'Deluxe Seafood Platter', 169.99);
insert into pedido (id_produto, nome, preco) values (989, 'Creamy Mushroom Risotto', 15.99);
insert into pedido (id_produto, nome, preco) values (990, 'Gourmet Truffle Fries', 4.49);
insert into pedido (id_produto, nome, preco) values (991, 'Wholesome Quinoa Salad', 3.49);
insert into pedido (id_produto, nome, preco) values (992, 'Decadent Chocolate Lava Cake', 19.99);
insert into pedido (id_produto, nome, preco) values (993, 'Savory Garlic Shrimp Pasta', 34.99);
insert into pedido (id_produto, nome, preco) values (994, 'Creamy Mushroom Risotto', 2.29);
insert into pedido (id_produto, nome, preco) values (995, 'Sweet Honey BBQ Wings', 19.99);
insert into pedido (id_produto, nome, preco) values (996, 'Sweet Honey BBQ Wings', 19.99);
insert into pedido (id_produto, nome, preco) values (997, 'Homestyle Apple Pie', 89.99);
insert into pedido (id_produto, nome, preco) values (998, 'Refreshing Watermelon Salad', 2.99);
insert into pedido (id_produto, nome, preco) values (999, 'Flavorful Veggie Stir-Fry', 39.99);
insert into pedido (id_produto, nome, preco) values (1000, 'Crispy Parmesan Chicken', 89.99);
